<?php

namespace Database\Seeders;

use App\Models\Meeting\Survey\Question\Option\Option;
use Illuminate\Database\Seeder;

class MeetingSurveyQuestionOptionsSeeder extends Seeder
{
    public function run(): void
    {
        Option::insert([
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '1',
                'option' => 'Erkek OP’u önemli bir mortalite nedenidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '1',
                'option' => 'Osteporoz erkeklerde kadınlarda ki kadar önemli bir sağlık sorunu değildir.',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '1',
                'option' => 'ADT bağlı OP çok nadir görüldüğünden taramaya gerek yoktur.',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '1',
                'option' => 'Pek çok sebeple  OP ortaya çıkabileceği için  ADT bağlı OP takibi gereksizdir.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '2',
                'option' => 'Her hastaya bazal DEXA çekilmelidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '2',
                'option' => 'Yalnızca 75 yaş üzeri hastalara çekilmelidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '2',
                'option' => 'Sadece risk faktörü olan hastalara çekilmelidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '2',
                'option' => '70 yaşın üzerinde risk faktörü olmayan hastalara çekilmesine gerek yoktur.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '3',
                'option' => 'Vertebral yeterlidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '3',
                'option' => 'Ön kol yeterlidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '3',
                'option' => 'Vertebra ve kalça yeterlidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '3',
                'option' => 'Vertebral ve kalça yorumlanamıyorsa ön kol mutlaka çekilmelidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '4',
                'option' => 'Bazal düzey ölçümü yeterlidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '4',
                'option' => 'Bazal ve 12.ya da 18.ay tekrarlayan ölçümü yapılmalıdır.',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '4',
                'option' => '6 ayda bir kontrol ölçümü yapılmalıdır.',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '4',
                'option' => 'D vit düzeyi ölçümü şart değildir.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '5',
                'option' => 'Hormonal tedavi ya da kemiğe yönelik tedavi öncesinde bakılmasına gerek yoktur.',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '5',
                'option' => 'ADT altında OP saptanırsa 25 OH D vit düzeyine bakılmalıdır.',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '5',
                'option' => 'Kemik metastazı saptandığında bifosfonat başlanmadan ölçülmelidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '5',
                'option' => 'ADT bağlı OP’da 25 OH D vit yerine 1,25(OH)2 D  düzeyi ölçülmelidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '6',
                'option' => 'M0 Hormona Duyarlı Prostat Kanserinde Ek risk faktörü yoksa OP takibine gerek yoktur.',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '6',
                'option' => 'M0 Kastrasyon Dirençli Prostat Kanserinde OP taraması yapılmalıdır.',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '6',
                'option' => 'Adjuvan tedavi alan hastalarda  OP taramasına gerek yoktur.',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '6',
                'option' => 'Adjuvan tedavi alan tüm hasta gruplarında kemik sağlığı yakın izlenmelidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '7',
                'option' => 'Geriatri Kliniklerinin takip etmesi gereken bir sağlık sorunudur.',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '7',
                'option' => 'Onkoloji Kliniği takibinde OP takibi gereksizdir.',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '7',
                'option' => 'Yalnızca metastatik hastalıkta ADT alan hastalarda OP taraması önemlidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '7',
                'option' => 'ADT’ye bağlı OP taraması primer hekimince yapılıp tedavisi multidisipliner olarak sürdürülmelidir.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '8',
                'option' => 'Evet',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '8',
                'option' => 'Hayır',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '8',
                'option' => 'Bazı hastalarıma önerebildim.',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '8',
                'option' => 'Poliklinik yoğunluğundan dolayı OP taramasını yapmaya fırsat bulamıyorum.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '9',
                'option' => 'ALP, kalsiyum, fosfor, PTH',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '9',
                'option' => 'ALP, PTH, serum kalsiyum düzeyi, 25OH D vit düzeyleri',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '9',
                'option' => 'T.testosteron, Estradiol',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '9',
                'option' => 'Kemik sağlığı açısından özel bir takip yapmadım.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '10',
                'option' => '20 Ekim',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '10',
                'option' => '21 Ekim',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '10',
                'option' => '22 Ekim',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '10',
                'option' => '23 Ekim',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '11',
                'option' => 'Üniversite hastanesi',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '11',
                'option' => 'Eğitim araştırma hastanesi',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '11',
                'option' => 'Devlet hastanesi',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '11',
                'option' => 'Özel hastane',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '12',
                'option' => 'Uptodate',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '12',
                'option' => 'Nccn',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '12',
                'option' => 'Esmo',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '12',
                'option' => 'Pubmed',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '13',
                'option' => 'BSA ne çıkarsa aynı dozda veririm.',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '13',
                'option' => 'Yan etkileri yönetmesi daha kolay olduğunu düşündüğüm için dozları biraz modifiye ederim.',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '13',
                'option' => 'Her hastaya BSA 1,5 olacak şekilde veririm.',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '13',
                'option' => 'Uygulanacak İlaca göre yaklaşımım değişir.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '14',
                'option' => 'Hocaya danışırım.',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '14',
                'option' => 'Kemoterapi sorumlu hemşiresine danışırım.',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '14',
                'option' => 'İnternet tarayıcılarına yazıp mevcut protokollere bakarım.',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '14',
                'option' => 'İlaç firmalarının medikal departmanına danışırım.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '15',
                'option' => 'Hocanın görüşü',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '15',
                'option' => 'Başka bir üniversitede bu konuda deneyim sahibi onkolog arkadaşımın görüşü',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '15',
                'option' => 'Literatür bilgileri',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '15',
                'option' => 'İlaç firması görüşü',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '16',
                'option' => 'Meme kanseri adjuvan tedavi',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '16',
                'option' => 'Kolon kanseri adjuvan tedavi',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '16',
                'option' => 'Sarkom adjuvan tedavi',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '16',
                'option' => 'Akciğer adjuvan tedavi',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '17',
                'option' => '18-30 yaş',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '17',
                'option' => '30-50 yaş',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '17',
                'option' => '50-70 yaş',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '17',
                'option' => '70 yaş üstü',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '18',
                'option' => 'İhtiyaç durumunda Uptodate, nncn bakarım',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '18',
                'option' => 'Düzenli online toplantıları takip ederim.',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '18',
                'option' => 'Diğer onkolog arkadaşlara danışırım.',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '18',
                'option' => 'Textbook okurum.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '19',
                'option' => 'Yan dal yaptığım merkezdeki protokolleri kullanırım.',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '19',
                'option' => 'Devlet hastanesinde belden önceki onkolog hangi protolleri kullanmışsa onları kullanırım.',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '19',
                'option' => 'Kendim protokol oluştururum.',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '19',
                'option' => 'Derneklerin sitelerinde yer alan protokolleri kullanırım.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '20',
                'option' => '0-3',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '20',
                'option' => '3-6',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '20',
                'option' => '6-8',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '20',
                'option' => '8-10',
                'status' => 1,
            ],
        ]);
    }
}
