<?php

namespace Database\Seeders;

use App\Models\Meeting\Survey\Question\Option\Option;
use Illuminate\Database\Seeder;

class MeetingSurveyQuestionOptionsSeeder extends Seeder
{
    public function run(): void
    {
        Option::insert([
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '1',
                'option' => 'Medikal Onkoloji',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '1',
                'option' => 'Diğer',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '2',
                'option' => 'Akademisyen',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '2',
                'option' => 'Uzman Hekim',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '2',
                'option' => 'Fellow Hekim',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '3',
                'option' => 'Kamu Hastanesi',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '3',
                'option' => 'Üniversite Hastanesi',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '3',
                'option' => 'Özel Hastane',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '3',
                'option' => 'Özel Muayenehane',
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'survey_id' => '1',
                'question_id' => '3',
                'option' => 'İlaç Firması',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '4',
                'option' => '1-2 hekim',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '4',
                'option' => '3-5 hekim',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '4',
                'option' => '6-9 hekim',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '4',
                'option' => '10 hekim ve üzeri',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '5',
                'option' => '26-35 saat',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '5',
                'option' => '36-45 saat',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '5',
                'option' => '46-55 saat',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '5',
                'option' => '56 saatin üzerinde',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '6',
                'option' => 'Sağlık Hizmeti: %95-100 / Bilimsel Aktivite: %0-5',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '6',
                'option' => 'Sağlık Hizmeti: %90-94 / Bilimsel Aktivite: %6-10',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '6',
                'option' => 'Sağlık Hizmeti: %85-90 / Bilimsel Aktivite: %11-15',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '6',
                'option' => 'Sağlık Hizmeti: %80-84 / Bilimsel Aktivite: %16-20',
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'survey_id' => '1',
                'question_id' => '6',
                'option' => "Sağlık Hizmeti: %80'den az / Bilimsel Aktivite: %20'den fazla",
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '7',
                'option' => '50.000 TL’den az',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '7',
                'option' => '50.000 TL-75.000 TL',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '7',
                'option' => '75.000 TL-100.000 TL',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '7',
                'option' => '100.000 TL-150.000 TL',
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'survey_id' => '1',
                'question_id' => '7',
                'option' => "150.000 TL'den fazla",
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '8',
                'option' => '0-20 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '8',
                'option' => '21-40 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '8',
                'option' => '41-60 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '8',
                'option' => '61 hasta ve daha fazla',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '9',
                'option' => '0-5 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '9',
                'option' => '6-10 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '9',
                'option' => '11-15 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '9',
                'option' => '16 hasta ve daha fazla',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '10',
                'option' => '0-5 konsültasyon',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '10',
                'option' => '6-10 konsültasyon',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '10',
                'option' => '11-20 konsültasyon',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '10',
                'option' => '21 ve üzeri konsültasyon',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '11',
                'option' => '0-300 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '11',
                'option' => '301-450 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '11',
                'option' => '451-600 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '11',
                'option' => '601-1200 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'survey_id' => '1',
                'question_id' => '11',
                'option' => '1201 hasta ve daha fazla',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '12',
                'option' => '0-30 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '12',
                'option' => '31-60 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '12',
                'option' => '61-150 hasta',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '12',
                'option' => '151 hasta ve daha fazla',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '13',
                'option' => '0-60',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '13',
                'option' => '61-150',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '13',
                'option' => '151-300',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '13',
                'option' => '301 ve üzeri',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '1',
                'question_id' => '14',
                'option' => '0-60',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '1',
                'question_id' => '14',
                'option' => '61-150',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '1',
                'question_id' => '14',
                'option' => '151-300',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '1',
                'question_id' => '14',
                'option' => '301 ve üzeri',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '15',
                'option' => '30-35',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '15',
                'option' => '35-40',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '15',
                'option' => '40-50',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '15',
                'option' => '50 yaş üstü',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '16',
                'option' => 'Araştırma görevlisi/Fellow ',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '16',
                'option' => 'Uzman',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '16',
                'option' => 'Doktor Öğretim Üyesi',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '16',
                'option' => 'Doçent',
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'survey_id' => '2',
                'question_id' => '16',
                'option' => 'Profesör',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '17',
                'option' => '0-3 yıl',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '17',
                'option' => '4-10 yıl',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '17',
                'option' => '10-20 yıl',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '17',
                'option' => '20 yıl üzeri',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '18',
                'option' => 'Üniversite Hastanesi',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '18',
                'option' => 'Eğitim Araştırma Hastanesi/Afiliye Araştırma Hastanesi',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '18',
                'option' => 'Özel Hastane',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '18',
                'option' => 'Devlet Hastanesi',
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'survey_id' => '2',
                'question_id' => '18',
                'option' => 'Muayenehane',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '19',
                'option' => "5'ten az",
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '19',
                'option' => '5-30',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '19',
                'option' => '30-50',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '19',
                'option' => "50'den fazla",
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '20',
                'option' => 'Çok az',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '20',
                'option' => 'Az',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '20',
                'option' => 'Ortalama',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '20',
                'option' => 'Fazla',
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'survey_id' => '2',
                'question_id' => '20',
                'option' => 'Çok fazla',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '21',
                'option' => 'ER durumu',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '21',
                'option' => 'PR durumu',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '21',
                'option' => 'Her2 durumu',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '2',
                'question_id' => '21',
                'option' => 'Ki67 durumu',
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'survey_id' => '2',
                'question_id' => '21',
                'option' => 'Grad',
                'status' => 1,
            ],
            [
                'sort_order' => '60',
                'survey_id' => '2',
                'question_id' => '21',
                'option' => 'Diğer',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '22',
                'option' => 'Tamoksifen',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '22',
                'option' => 'Aroma inhibitörleri',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '23',
                'option' => 'Tedavi vermiyorum.',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '23',
                'option' => 'Tamoksifen veya Aromataz inhibitörü',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '2',
                'question_id' => '23',
                'option' => 'Diğer',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '2',
                'question_id' => '24',
                'option' => 'Er/PR pozitif DCIS’da olduğu gibi',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '2',
                'question_id' => '24',
                'option' => 'ER/ PR pozitif DCIS göre daha yakın takip ediyorum.',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '3',
                'question_id' => '25',
                'option' => '3.basamak Üniversite veya Eğitim Araştırma Hastanesi',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '3',
                'question_id' => '25',
                'option' => '2. Basamak Devlet Hastanesi',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '3',
                'question_id' => '25',
                'option' => 'Özel Kurul',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '3',
                'question_id' => '26',
                'option' => '<3 yıl',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '3',
                'question_id' => '26',
                'option' => '3-10 yıl',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '3',
                'question_id' => '26',
                'option' => '>10 yıl',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '3',
                'question_id' => '27',
                'option' => 'Evet',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '3',
                'question_id' => '27',
                'option' => 'Hayır',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '3',
                'question_id' => '27',
                'option' => 'İleri merkez sevk',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '3',
                'question_id' => '28',
                'option' => 'Toraks Konseyi',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '3',
                'question_id' => '28',
                'option' => 'Gis Kanserleri Konseyi',
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'survey_id' => '3',
                'question_id' => '28',
                'option' => 'Beyin TM Konseyi',
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'survey_id' => '3',
                'question_id' => '28',
                'option' => 'Ürogenital/Jinekoloik/Meme TM konseyi',
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'survey_id' => '3',
                'question_id' => '28',
                'option' => 'Kas İskelet TM Konseyi',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '3',
                'question_id' => '29',
                'option' => 'Evet, düzenli haftalık',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '3',
                'question_id' => '29',
                'option' => 'Hasta çıktıkça yapılmakta',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '3',
                'question_id' => '30',
                'option' => 'Evet',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '3',
                'question_id' => '30',
                'option' => 'Hayır',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '3',
                'question_id' => '31',
                'option' => 'Konsey kararını',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '3',
                'question_id' => '31',
                'option' => 'Kliniğimiz kararını',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '3',
                'question_id' => '32',
                'option' => 'Evet',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '3',
                'question_id' => '32',
                'option' => 'Hayır',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '3',
                'question_id' => '33',
                'option' => 'Kendi klinik genetik kliniğimiz',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '3',
                'question_id' => '33',
                'option' => 'Dışarıdan konsultasyon usulü',
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'survey_id' => '3',
                'question_id' => '34',
                'option' => 'Evet',
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'survey_id' => '3',
                'question_id' => '34',
                'option' => 'Hayır',
                'status' => 1,
            ]
        ]);
    }
}
