<?php

namespace Database\Seeders;

use App\Models\Meeting\Hall\Program\Session\Session;
use Illuminate\Database\Seeder;

class MeetingHallProgramSessionSeeder extends Seeder
{
    public function run(): void
    {
        Session::insert([
            [
                'sort_order' => '10',
                'program_id' => 1,
                'speaker_id' => null,
                'code' => null,
                'title' => 'HR(+) Meme Kanserinde Adjuvan Tedavi',
                'description' => 'Panelistler; Banu Öztürk, Didem Tunalı, Meral Günaldı, Berna Bozkurt Duman',
                'start_at' => '2023-11-01 13:30',
                'finish_at' => '2023-11-01 14:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 1,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Triple Negatif Meme Kanserinde Neoadjuvan Tedavi ve Sonrası',
                'description' => 'Panelistler; Banu Öztürk, Didem Tunalı, Meral Günaldı, Berna Bozkurt Duman',
                'start_at' => '2023-11-01 14:00',
                'finish_at' => '2023-11-01 14:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 3,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Nüks Epitelyal Over Tümörlerine Yaklaşım',
                'description' => null,
                'start_at' => '2023-11-01 14:45',
                'finish_at' => '2023-11-01 15:15',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 3,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Seks Kord Stromal Tümörler',
                'description' => null,
                'start_at' => '2023-11-01 15:15',
                'finish_at' => '2023-11-01 15:35',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 3,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Erken Evre Endometrium Kanserinde Tedavi Planı',
                'description' => null,
                'start_at' => '2023-11-01 15:35',
                'finish_at' => '2023-11-01 15:55',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 3,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Metastatik Evre Endometrium Kanserine Yaklaşım',
                'description' => null,
                'start_at' => '2023-11-01 15:55',
                'finish_at' => '2023-11-01 16:15',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 3,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Serviks Kanserinde Sistemik Tedavi',
                'description' => null,
                'start_at' => '2023-11-01 16:15',
                'finish_at' => '2023-11-01 16:35',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 3,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Soru & Cevap & Tartışma',
                'description' => null,
                'start_at' => '2023-11-01 16:35',
                'finish_at' => '2023-11-01 17:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 4,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Agnostik Tedavi Kavramına Genel Bakış',
                'description' => null,
                'start_at' => '2023-11-01 13:30',
                'finish_at' => '2023-11-01 13:45',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 4,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Kapsamlı Moleküler Testler; Kime? Hangisi? Ne Zaman?',
                'description' => null,
                'start_at' => '2023-11-01 13:45',
                'finish_at' => '2023-11-01 14:05',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 4,
                'speaker_id' => null,
                'code' => null,
                'title' => 'MSI ve TMB',
                'description' => null,
                'start_at' => '2023-11-01 14:05',
                'finish_at' => '2023-11-01 14:25',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 4,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Diğer Agnostik Belirteçler (NTRK, RET, BRAF ve Ötesi)',
                'description' => null,
                'start_at' => '2023-11-01 14:25',
                'finish_at' => '2023-11-01 14:45',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 4,
                'speaker_id' => null,
                'code' => null,
                'title' => 'BRCA & HRD Agnostik Tedavi Belirteç Adayı mı?',
                'description' => null,
                'start_at' => '2023-11-01 14:45',
                'finish_at' => '2023-11-01 15:05',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '60',
                'program_id' => 4,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Soru & Cevap & Tartışma',
                'description' => null,
                'start_at' => '2023-11-01 15:05',
                'finish_at' => '2023-11-01 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 6,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Testis Kanserinde 1. Basamak Tedavi Yaklaşımı',
                'description' => null,
                'start_at' => '2023-11-01 15:45',
                'finish_at' => '2023-11-01 16:05',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 6,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Testis Kanserinde Salvage Tedavi',
                'description' => null,
                'start_at' => '2023-11-01 16:05',
                'finish_at' => '2023-11-01 16:25',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 6,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Metastatik Hepatoselüler Karsinomda Tedavi Planı',
                'description' => null,
                'start_at' => '2023-11-01 16:25',
                'finish_at' => '2023-11-01 16:45',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 6,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Soru & Cevap & Tartışma',
                'description' => null,
                'start_at' => '2023-11-01 16:45',
                'finish_at' => '2023-11-01 17:15',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
           [
                'sort_order' => '10',
                'program_id' => 8,
               'speaker_id' => null,
                'code' => 'panel-1-1',
                'title' => 'Kolorektal Kanserinde Neoadjuvan Tedavi',
               'description' => null,
                'start_at' => '2023-11-02 09:15',
                'finish_at' => '2023-11-02 09:35',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 1,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 8,
                'speaker_id' => null,
                'code' => 'panel-1-2',
                'title' => 'Kolon Kanserinde Adjuvan Tedavi: Kime ve Nasıl?',
                'description' => null,
                'start_at' => '2023-11-02 09:35',
                'finish_at' => '2023-11-02 09:55',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 8,
                'speaker_id' => null,
                'code' => 'panel-1-3',
                'title' => 'Metastatik Kolon Kanserinde Yeni Hedefe Yönelik Tedavi Seçenekleri',
                'description' => null,
                'start_at' => '2023-11-02 09:55',
                'finish_at' => '2023-11-02 10:15',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 8,
                'speaker_id' => null,
                'code' => 'panel-1-4',
                'title' => 'Soru & Cevap & Tartışma',
                'description' => null,
                'start_at' => '2023-11-02 10:15',
                'finish_at' => '2023-11-02 10:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 9,
                'speaker_id' => null,
                'code' => null,
                'title' => 'LYNPARZA ile Over ve Meme Kanserlerinde Fark Yaratmaya Var Mısınız?',
                'description' => null,
                'start_at' => '2023-11-02 10:30',
                'finish_at' => '2023-11-02 10:45',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 9,
                'speaker_id' => null,
                'code' => null,
                'title' => 'LYNPARZA ile Over ve Meme Kanserlerinde Fark Yaratmaya Var Mısınız?',
                'description' => null,
                'start_at' => '2023-11-02 10:45',
                'finish_at' => '2023-11-02 11:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 11,
                'speaker_id' => null,
                'code' => 'panel-2-1',
                'title' => 'İleri Evre Pankreas Kanserinde Tedaviler',
                'description' => null,
                'start_at' => '2023-11-02 11:20',
                'finish_at' => '2023-11-02 11:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 11,
                'speaker_id' => null,
                'code' => 'panel-2-2',
                'title' => 'Mide ve Özofagus Kanserlerinde İmmünoterapi',
                'description' => null,
                'start_at' => '2023-11-02 11:40',
                'finish_at' => '2023-11-02 12:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 11,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Soru & Cevap & Tartışma',
                'description' => null,
                'start_at' => '2023-11-02 12:00',
                'finish_at' => '2023-11-02 12:15',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 13,
                'speaker_id' => null,
                'code' => null,
                'title' => '1.Basamak mKHDAK Tedavisinde Klinik Verilerle CM 9LA ve Opdivo+Yervoy+2 Kür KT Deneyimi',
                'description' => null,
                'start_at' => '2023-11-02 13:30',
                'finish_at' => '2023-11-02 14:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 14,
                'speaker_id' => null,
                'code' => 'panel-3-1',
                'title' => 'Endikasyon Dışı İlaç Kullanımında Klinisyen Bakış Açısı',
                'description' => null,
                'start_at' => '2023-11-02 14:00',
                'finish_at' => '2023-11-02 14:20',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 14,
                'speaker_id' => null,
                'code' => 'panel-3-2',
                'title' => 'Endikasyon Dışı İlaç Kullanımında Hukuki Süreç',
                'description' => null,
                'start_at' => '2023-11-02 14:20',
                'finish_at' => '2023-11-02 14:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 14,
                'speaker_id' => null,
                'code' => 'panel-3-3',
                'title' => 'İnteraktif Tartışma',
                'description' => null,
                'start_at' => '2023-11-02 14:40',
                'finish_at' => '2023-11-02 15:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 15,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Erken Evre Akciğer Kanserinde Cerrahi Yaklaşım',
                'description' => null,
                'start_at' => '2023-11-02 15:10',
                'finish_at' => '2023-11-02 15:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 15,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Erken Evre Akciğer Kanserinde İmmunoterapi',
                'description' => null,
                'start_at' => '2023-11-02 15:10',
                'finish_at' => '2023-11-02 15:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 18,
                'speaker_id' => null,
                'code' => 'panel-4-1',
                'title' => 'KHDAK: Patolog Bakış Açısı',
                'description' => null,
                'start_at' => '2023-11-03 09:15',
                'finish_at' => '2023-11-03 09:35',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 18,
                'speaker_id' => null,
                'code' => 'panel-4-2',
                'title' => 'Hedefli Mutasyon Olmayan Metastatik KHDAK’de 1. Basamak Tedaviler',
                'description' => null,
                'start_at' => '2023-11-03 09:35',
                'finish_at' => '2023-11-03 09:55',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 18,
                'speaker_id' => null,
                'code' => 'panel-4-3',
                'title' => 'EGFR ve ALK Dışı Mutasyon Pozitif Hastalarda Tedavi',
                'description' => null,
                'start_at' => '2023-11-03 09:55',
                'finish_at' => '2023-11-03 10:15',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 18,
                'speaker_id' => null,
                'code' => 'panel-4-4',
                'title' => 'Soru & Cevap & Tartışma',
                'description' => null,
                'start_at' => '2023-11-03 10:15',
                'finish_at' => '2023-11-03 10:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 19,
                'speaker_id' => null,
                'code' => null,
                'title' => '1.Basamak mKHDAK Tedavisinde Pembrolizumab’ın Olgularla 5 Yıllık Güncel Sonuçları',
                'description' => null,
                'start_at' => '2023-11-03 10:30',
                'finish_at' => '2023-11-03 11:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 19,
                'speaker_id' => null,
                'code' => null,
                'title' => '1.Basamak mKHDAK Tedavisinde Pembrolizumab’ın Olgularla 5 Yıllık Güncel Sonuçları',
                'description' => null,
                'start_at' => '2023-11-03 10:30',
                'finish_at' => '2023-11-03 11:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 21,
                'speaker_id' => null,
                'code' => 'panel-5-1',
                'title' => 'Adjuvanda Endokrin Tedavi',
                'description' => null,
                'start_at' => '2023-11-03 11:15',
                'finish_at' => '2023-11-03 11:35',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 21,
                'speaker_id' => null,
                'code' => 'panel-5-2',
                'title' => 'Neoadjuvant Tedavi Sonrası Rezidü Hastalığa Yaklaşım',
                'description' => null,
                'start_at' => '2023-11-03 11:35',
                'finish_at' => '2023-11-03 11:55',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 21,
                'speaker_id' => null,
                'code' => 'panel-5-3',
                'title' => 'Soru & Cevap & Tartışma',
                'description' => null,
                'start_at' => '2023-11-03 11:55',
                'finish_at' => '2023-11-03 12:05',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 22,
                'speaker_id' => null,
                'code' => null,
                'title' => 'HR(+) HER2(-) Metastatik Meme Kanserinde Yaşam için VALAMOR',
                'description' => null,
                'start_at' => '2023-11-03 12:05',
                'finish_at' => '2023-11-03 12:35',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 22,
                'speaker_id' => null,
                'code' => null,
                'title' => 'HR(+) HER2(-) Metastatik Meme Kanserinde Yaşam için VALAMOR',
                'description' => null,
                'start_at' => '2023-11-03 12:05',
                'finish_at' => '2023-11-03 12:35',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 24,
                'speaker_id' => null,
                'code' => 'panel-6-1',
                'title' => 'Metastatik Triple Negatif Meme Kanserinde Yaklaşım',
                'description' => null,
                'start_at' => '2023-11-03 13:30',
                'finish_at' => '2023-11-03 13:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 24,
                'speaker_id' => null,
                'code' => 'panel-6-2',
                'title' => 'Metastatik HER2(+) Meme Kanseri Tedavisinde Gelişmeler',
                'description' => null,
                'start_at' => '2023-11-03 13:50',
                'finish_at' => '2023-11-03 14:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 24,
                'speaker_id' => null,
                'code' => 'panel-6-3',
                'title' => 'Soru & Cevap & Tartışma',
                'description' => null,
                'start_at' => '2023-11-03 14:10',
                'finish_at' => '2023-11-03 14:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 25,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Metastatik Üçlü Negatif Meme Kanserinde Standartları Yükseltiyoruz',
                'description' => null,
                'start_at' => '2023-11-03 14:30',
                'finish_at' => '2023-11-03 15:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 27,
                'speaker_id' => null,
                'code' => null,
                'title' => 'CROWN ışığında Lorviqua: ALK+ mKHDAK 1. Basamak Tedavisinde Güncel Gelişmeler',
                'description' => null,
                'start_at' => '2023-11-03 15:15',
                'finish_at' => '2023-11-03 15:45',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 28,
                'speaker_id' => null,
                'code' => 'panel-7-1',
                'title' => 'Erken Evre Melanomda Tedavi Seçenekleri',
                'description' => null,
                'start_at' => '2023-11-03 15:45',
                'finish_at' => '2023-11-03 16:05',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 28,
                'speaker_id' => null,
                'code' => 'panel-7-2',
                'title' => 'Metastatik Melanomda Güncel Tedavi: 1. Basamak ve Ötesi',
                'description' => null,
                'start_at' => '2023-11-03 16:05',
                'finish_at' => '2023-11-03 16:25',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 28,
                'speaker_id' => null,
                'code' => 'panel-7-3',
                'title' => 'Soru & Cevap & Tartışma',
                'description' => null,
                'start_at' => '2023-11-03 16:25',
                'finish_at' => '2023-11-03 16:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 34,
                'speaker_id' => null,
                'code' => 'panel-8-1',
                'title' => 'Metastatik Böbrek Kanseri Tedavisinde Gelişmeler',
                'description' => null,
                'start_at' => '2023-11-04 09:15',
                'finish_at' => '2023-11-04 09:35',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 34,
                'speaker_id' => null,
                'code' => 'panel-8-2',
                'title' => 'Metastatik Hormon Duyarlı Prostat Kanserinde Tedavi Yaklaşımı',
                'description' => null,
                'start_at' => '2023-11-04 09:35',
                'finish_at' => '2023-11-04 09:55',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 34,
                'speaker_id' => null,
                'code' => 'panel-8-3',
                'title' => 'Metastatik Prostat Kanserinde PARP İnhibitörlerinin Yeri',
                'description' => null,
                'start_at' => '2023-11-04 09:55',
                'finish_at' => '2023-11-04 10:15',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 34,
                'speaker_id' => null,
                'code' => 'panel-8-4',
                'title' => 'Metastatik Mesane Kanseri Tedavisinde Kemoterapinin Ötesi',
                'description' => null,
                'start_at' => '2023-11-04 10:15',
                'finish_at' => '2023-11-04 10:35',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 34,
                'speaker_id' => null,
                'code' => 'panel-8-5',
                'title' => 'Soru & Cevap & Tartışma',
                'description' => null,
                'start_at' => '2023-11-04 10:35',
                'finish_at' => '2023-11-04 11:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 36,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Prostat Kanseri Tedavisinde Önce XTANDI™',
                'description' => null,
                'start_at' => '2023-11-04 11:15',
                'finish_at' => '2023-11-04 11:45',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 37,
                'speaker_id' => null,
                'code' => 'panel-9-1',
                'title' => 'Over Kanserinde HIPEC’ın Yeri Var mı?',
                'description' => null,
                'start_at' => '2023-11-04 11:45',
                'finish_at' => '2023-11-04 12:05',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 37,
                'speaker_id' => null,
                'code' => 'panel-9-2',
                'title' => 'Endometrium Kanserinde Kemoterapinin Ötesi',
                'description' => null,
                'start_at' => '2023-11-04 12:05',
                'finish_at' => '2023-11-04 12:25',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 37,
                'speaker_id' => null,
                'code' => 'panel-9-3',
                'title' => 'Soru & Cevap & Tartışma',
                'description' => null,
                'start_at' => '2023-11-04 12:25',
                'finish_at' => '2023-11-04 12:35',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 39,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Over Kanseri İdame Tedavisinde Zejula ile Yeni Bir Dönem',
                'description' => null,
                'start_at' => '2023-11-04 13:30',
                'finish_at' => '2023-11-04 14:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 39,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Over Kanseri İdame Tedavisinde Zejula ile Yeni Bir Dönem',
                'description' => null,
                'start_at' => '2023-11-04 13:30',
                'finish_at' => '2023-11-04 14:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 39,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Over Kanseri İdame Tedavisinde Zejula ile Yeni Bir Dönem',
                'description' => null,
                'start_at' => '2023-11-04 13:30',
                'finish_at' => '2023-11-04 14:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 40,
                'speaker_id' => null,
                'code' => 'panel-10-1',
                'title' => 'Baş Boyun Kanserinde İmmunoterapi',
                'description' => null,
                'start_at' => '2023-11-04 14:00',
                'finish_at' => '2023-11-04 14:20',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 40,
                'speaker_id' => null,
                'code' => 'panel-10-2',
                'title' => 'Sarkomda Kişiselleştirilmiş Tedavi',
                'description' => null,
                'start_at' => '2023-11-04 14:20',
                'finish_at' => '2023-11-04 14:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 40,
                'speaker_id' => null,
                'code' => 'panel-10-3',
                'title' => 'Kanser Tedavisi Sırasında Beraber Kullandığımız İlaçların Olumsuz Etkileşiminin Farkında mıyız?',
                'description' => null,
                'start_at' => '2023-11-04 14:40',
                'finish_at' => '2023-11-04 15:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 40,
                'speaker_id' => null,
                'code' => 'panel-10-4',
                'title' => 'Soru & Cevap & Tartışma',
                'description' => null,
                'start_at' => '2023-11-04 15:00',
                'finish_at' => '2023-11-04 15:15',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 42,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Erken Evre TNBC Tedavisinde Pembrolizumab',
                'description' => null,
                'start_at' => '2023-11-04 15:30',
                'finish_at' => '2023-11-04 16:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 46,
                'speaker_id' => null,
                'code' => 'panel-12-1',
                'title' => 'Kanser Ağrısında Opiatlar',
                'description' => null,
                'start_at' => '2023-11-05 09:30',
                'finish_at' => '2023-11-05 10:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 46,
                'speaker_id' => null,
                'code' => 'panel-12-2',
                'title' => 'Tirozin Kinaz Grubu İlaçlarda Yan Etki Yönetimi',
                'description' => null,
                'start_at' => '2023-11-05 10:00',
                'finish_at' => '2023-11-05 10:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 46,
                'speaker_id' => null,
                'code' => 'panel-12-3',
                'title' => 'Kanserli Hastalarda Beslenme Desteği',
                'description' => null,
                'start_at' => '2023-11-05 10:30',
                'finish_at' => '2023-11-05 11:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 46,
                'speaker_id' => null,
                'code' => 'panel-12-4',
                'title' => 'Akılcı İlaç Sunumu',
                'description' => null,
                'start_at' => '2023-11-05 11:00',
                'finish_at' => '2023-11-05 11:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 48,
                'speaker_id' => null,
                'code' => 'S-01',
                'title' => 'Transvers Kolon Yerleşimli Opere Nonmetastatik Kolon Karsinomlu Hastalarda Hastalıksız Sağkalım Analizi - Tek Merkez Deneyimi',
                'description' => null,
                'start_at' => '2023-11-02 10:30',
                'finish_at' => '2023-11-02 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 48,
                'speaker_id' => null,
                'code' => 'S-02',
                'title' => 'Erken Evre Kolon Kanseri Hastalarında Pre-operatif Dönemde Bakılan Kolon Inflamatuar Indeksinin Nükssüz Sağkalımla Ilişkisi',
                'description' => null,
                'start_at' => '2023-11-02 10:30',
                'finish_at' => '2023-11-02 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 48,
                'speaker_id' => null,
                'code' => 'S-03',
                'title' => 'Kolon Kanserinde PD-1 Ekspresyon Düzeyi Ile Evre Arasındaki Ilişkinin Değerlendirilmesi',
                'description' => null,
                'start_at' => '2023-11-02 10:30',
                'finish_at' => '2023-11-02 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 48,
                'speaker_id' => null,
                'code' => 'S-04',
                'title' => 'Neoadjuvan Tedavi Alan Rektum Kanserli Hastalarda Beden Kitle Indeksinin Önemi',
                'description' => null,
                'start_at' => '2023-11-02 10:30',
                'finish_at' => '2023-11-02 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 48,
                'speaker_id' => null,
                'code' => 'S-05',
                'title' => '70 Yaş Üstü Evre-2 Ve Evre-3 Kolon Kanserli Hastalarda Oksaliplatinli Ve Oksaliplatinsiz Adjuvan Kemoterapi Rejimlerinin Karşilaştirilmali Etkinlik Analizi',
                'description' => null,
                'start_at' => '2023-11-02 10:30',
                'finish_at' => '2023-11-02 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '60',
                'program_id' => 48,
                'speaker_id' => null,
                'code' => 'S-06',
                'title' => 'Metastatik Kolorektal Kanserde Hiperüriseminin Prognostik Önemi',
                'description' => null,
                'start_at' => '2023-11-02 10:30',
                'finish_at' => '2023-11-02 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '70',
                'program_id' => 48,
                'speaker_id' => null,
                'code' => 'S-07',
                'title' => 'Metastatik Kolorektal Kanserde Prognostik Biyobelirteçler: Delta Prognostik Nutrisyon İndeksi, Delta Nötrofil/Lenfosit Oranı Ve Delta Trombosit/Lenfosit Oranı',
                'description' => null,
                'start_at' => '2023-11-02 10:30',
                'finish_at' => '2023-11-02 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '80',
                'program_id' => 48,
                'speaker_id' => null,
                'code' => 'S-08',
                'title' => 'Metastatik Kolorektal Kanser Hastalarında Standart Kemoterapi Ile Bevasizumab Kombine Tedavinin Karaciğer Küratif Tedavi Ve Sağkalıma Etkisi',
                'description' => null,
                'start_at' => '2023-11-02 10:30',
                'finish_at' => '2023-11-02 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '90',
                'program_id' => 48,
                'speaker_id' => null,
                'code' => 'S-09',
                'title' => 'Tek Merkez Deneyimi; Nöroendokrin Tümörlü Olgularin Serisi',
                'description' => null,
                'start_at' => '2023-11-02 10:30',
                'finish_at' => '2023-11-02 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '100',
                'program_id' => 49,
                'speaker_id' => null,
                'code' => 'S-10',
                'title' => 'Küratif Rezeksiyon Yapılmış Mide Kanseri Vakalarında PD-L1 Ekspresyonunun Klinikopatolojik Parametreler Ve Sağkalımla Ilişkisi',
                'description' => null,
                'start_at' => '2023-11-02 13:30',
                'finish_at' => '2023-11-02 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '110',
                'program_id' => 49,
                'speaker_id' => null,
                'code' => 'S-11',
                'title' => 'Perioperatif Kemoterapi Alan Lokal İleri Mide Kanserli Hastalarda Psoas Kas İndeksinin Klinik Önemi ',
                'description' => null,
                'start_at' => '2023-11-02 13:30',
                'finish_at' => '2023-11-02 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '120',
                'program_id' => 49,
                'speaker_id' => null,
                'code' => 'S-12',
                'title' => 'Metastatik Mide Kanseri Ile Takip Edilen Hastalarda Bilgisayarlı Tomografi Ile Değerlendirilen Lomber Kas Kalınlığının Sağ Kalım Üzerine Etkisi',
                'description' => null,
                'start_at' => '2023-11-02 13:30',
                'finish_at' => '2023-11-02 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '130',
                'program_id' => 49,
                'speaker_id' => null,
                'code' => 'S-13',
                'title' => 'Metastatik Her-2 Pozitif Mide Kanseri Olgularının Retrospektif Analizi: Tek Merkez Deneyimi',
                'description' => null,
                'start_at' => '2023-11-02 13:30',
                'finish_at' => '2023-11-02 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '140',
                'program_id' => 49,
                'speaker_id' => null,
                'code' => 'S-14',
                'title' => 'Her-2 Pozitif Mide Kanseri Tedavisine Trastuzumab Eklenmesinin Hastalık Progresyonuna Katkısı; Tek Merkez Deneyimi ',
                'description' => null,
                'start_at' => '2023-11-02 13:30',
                'finish_at' => '2023-11-02 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '150',
                'program_id' => 49,
                'speaker_id' => null,
                'code' => 'S-15',
                'title' => 'Erken Evre Pankreatikobiliyer Sistem Kanseri Tanılı Hastalarda Genel ve Hastalıksız Sağkalım',
                'description' => null,
                'start_at' => '2023-11-02 13:30',
                'finish_at' => '2023-11-02 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '160',
                'program_id' => 49,
                'speaker_id' => null,
                'code' => 'S-16',
                'title' => 'İleri Evre Hepatosellüler Karsinom Tanılı Hastalarda Sistemik Tedavi Etkililik Ve Güvenlilik Değerlendirmesi',
                'description' => null,
                'start_at' => '2023-11-02 13:30',
                'finish_at' => '2023-11-02 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '170',
                'program_id' => 49,
                'speaker_id' => null,
                'code' => 'S-17',
                'title' => 'İleri Evre Hepatoselüler Karsinom Tanılı Hastalarda Sağkalımı Etkileyen Faktörler',
                'description' => null,
                'start_at' => '2023-11-02 13:30',
                'finish_at' => '2023-11-02 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '180',
                'program_id' => 49,
                'speaker_id' => null,
                'code' => 'S-18',
                'title' => 'Kolanjiyokarsinom Hastalarında Platelet/albümin Oranının (Par) Prognostik Önemi',
                'description' => null,
                'start_at' => '2023-11-02 13:30',
                'finish_at' => '2023-11-02 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '190',
                'program_id' => 50,
                'speaker_id' => null,
                'code' => 'S-19',
                'title' => 'Akciğer Kanserinde Moleküler Testlerin Gerçek Yaşam Verileri: Tek Merkez Deneyimi',
                'description' => null,
                'start_at' => '2023-11-03 10:30',
                'finish_at' => '2023-11-03 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '200',
                'program_id' => 50,
                'speaker_id' => null,
                'code' => 'S-20',
                'title' => 'Opere Olan Küçük Hücre Dışı Akciğer Kanserli Hastalarda Primer Lezyonunun Pet/bt’deki Suv- Max Değerinin Sağkalım Için Prognostik Değeri',
                'description' => null,
                'start_at' => '2023-11-03 10:30',
                'finish_at' => '2023-11-03 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '210',
                'program_id' => 50,
                'speaker_id' => null,
                'code' => 'S-21',
                'title' => 'Metastatik Küçük Hücre Dışı Akciğer Kanseri Tanılı Hastalarda Afatinib Ve Erlotinib Tek Merkez Deneyimi',
                'description' => null,
                'start_at' => '2023-11-03 10:30',
                'finish_at' => '2023-11-03 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '220',
                'program_id' => 50,
                'speaker_id' => null,
                'code' => 'S-22',
                'title' => 'İkinci Basamak Tedavi Olarak Nivolumab Kullanan Küçük Hücreli Dışı Akciğer Kanserli Hastalarda Bazal Metabolizma Hızı ile Sağkalım İlişkisi',
                'description' => null,
                'start_at' => '2023-11-03 10:30',
                'finish_at' => '2023-11-03 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '230',
                'program_id' => 50,
                'speaker_id' => null,
                'code' => 'S-23',
                'title' => 'Metastatik Ya Da Unrezekrabl Akciğer Kanseri Tedavisinde Nivolumab Tedavi Yanıtlılığı Ve Sistemik Inflamatuar Index Değişimi Arasındaki Ilişki',
                'description' => null,
                'start_at' => '2023-11-03 10:30',
                'finish_at' => '2023-11-03 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '240',
                'program_id' => 50,
                'speaker_id' => null,
                'code' => 'S-24',
                'title' => 'Küçük Hücreli Akciğer Kanseri (Khak) Hücre Hattında Bcl-2 Inhibitörü Olan Venetoclax’ın Kemoduyarlılaştırma Ve Sitotoksik Etkisinin Değerlendirilmesi',
                'description' => null,
                'start_at' => '2023-11-03 10:30',
                'finish_at' => '2023-11-03 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '250',
                'program_id' => 50,
                'speaker_id' => null,
                'code' => 'S-25',
                'title' => ' Gastrointestinal Stromal Tümör Tanılı Hastaların Klinikopatolojik Özellikleri: Tek Merkez Deneyimi ',
                'description' => null,
                'start_at' => '2023-11-03 10:30',
                'finish_at' => '2023-11-03 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '260',
                'program_id' => 50,
                'speaker_id' => null,
                'code' => 'S-26',
                'title' => 'Gastrointestinal Stromal Tümör Tanısı Alan Hastaların Demografik Değerlendirilmesi ‘Tek Merkez Deneyimi’ ',
                'description' => null,
                'start_at' => '2023-11-03 10:30',
                'finish_at' => '2023-11-03 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '270',
                'program_id' => 50,
                'speaker_id' => null,
                'code' => 'S-27',
                'title' => 'Metastatik Gastrointestinal Stromal Tümörlerde Sağ Kalımı Etkileyen Faktörler: Tek Merkez Deneyimi',
                'description' => null,
                'start_at' => '2023-11-03 10:30',
                'finish_at' => '2023-11-03 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '280',
                'program_id' => 50,
                'speaker_id' => null,
                'code' => 'S-28',
                'title' => 'Metastatik Gastrointestinal Stromal Tümörlerde Sağ Kalımı Etkileyen Faktörler: Tek Merkez Deneyimi',
                'description' => null,
                'start_at' => '2023-11-03 10:30',
                'finish_at' => '2023-11-03 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '290',
                'program_id' => 51,
                'speaker_id' => null,
                'code' => 'S-29',
                'title' => 'İnvaziv Lobüler Meme Kanseri Görüntülemesinde 68Ga-FAPI-PET/BT, 18FDG-PET/BT’ye Alternatif Olabilir mi? ',
                'description' => null,
                'start_at' => '2023-11-03 13:30',
                'finish_at' => '2023-11-03 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '300',
                'program_id' => 51,
                'speaker_id' => null,
                'code' => 'S-30',
                'title' => 'Meme Kanserinde Mikrovasküler dansite ve FOXP3+ T Hücrelerinin Klinik ve Prognostik Etkileri ',
                'description' => null,
                'start_at' => '2023-11-03 13:30',
                'finish_at' => '2023-11-03 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '310',
                'program_id' => 51,
                'speaker_id' => null,
                'code' => 'S-31',
                'title' => 'Lokal Ileri Triple Negatif Meme Kanserli Hastalarda Doku Lipokalin-2 Ekspresyonunun Neoadjuvan Kemoterapi Sonrası Patolojik Yanıt Ilişkisi Ve Prognoz Üzerine Etkisi',
                'description' => null,
                'start_at' => '2023-11-03 13:30',
                'finish_at' => '2023-11-03 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '320',
                'program_id' => 51,
                'speaker_id' => null,
                'code' => 'S-32',
                'title' => 'Cdk4/6 Inhibitörü Tedavisi Alan Metastatik Meme Kanserli Hastalarda Albümin/alkalen Fosfataz Oranının Prognostik Ve Prediktif Önemi',
                'description' => null,
                'start_at' => '2023-11-03 13:30',
                'finish_at' => '2023-11-03 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '330',
                'program_id' => 51,
                'speaker_id' => null,
                'code' => 'S-33',
                'title' => 'Metastatik Hormon Pozitif Meme Kanserli CDK-4/6 İnhibitörü Kullanan Hastalarda İnflamatuar Markırların Prediktif Rolü',
                'description' => null,
                'start_at' => '2023-11-03 13:30',
                'finish_at' => '2023-11-03 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '340',
                'program_id' => 51,
                'speaker_id' => null,
                'code' => 'S-34',
                'title' => 'Platin Dirençli Metastatik Over Kanserinde FOLFOX- XELOX Rejimlerinin Etkinliğinin Retrospektif Olarak Değerlendirilmesi',
                'description' => null,
                'start_at' => '2023-11-03 13:30',
                'finish_at' => '2023-11-03 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '350',
                'program_id' => 51,
                'speaker_id' => null,
                'code' => 'S-35',
                'title' => 'Rekürren veya Metastatik Nazofarenks Karsinomlu hastalarda İmmunoterapi Deneyimi',
                'description' => null,
                'start_at' => '2023-11-03 13:30',
                'finish_at' => '2023-11-03 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '360',
                'program_id' => 51,
                'speaker_id' => null,
                'code' => 'S-36',
                'title' => 'Glioblastoma Multiforme Nedeni İle Takip Edilen Hastalarda Manyetik Rezonans İle Belirlenmiş Sarkopeninin Prognostik Önemi',
                'description' => null,
                'start_at' => '2023-11-03 13:30',
                'finish_at' => '2023-11-03 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '370',
                'program_id' => 51,
                'speaker_id' => null,
                'code' => 'S-37',
                'title' => 'Metastatik Anjiosarkom Hastalarında Paklitaksel Tedavisi Gerçek Yaşam Verileri: Tek Merkez Deneyimi',
                'description' => null,
                'start_at' => '2023-11-03 13:30',
                'finish_at' => '2023-11-03 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '380',
                'program_id' => 52,
                'speaker_id' => null,
                'code' => 'S-38',
                'title' => 'İleri Evre Şeffaf Hücreli Dışı Böbrek Kanseri Tanılı Hastalarda Birinci Basamak Tedavide Pazopanib Ve Sunitinib Tedavilerinin Etkinliklerinin Karşılaştırılması, Çok Merkezli Gerçek Yaşam Verisi',
                'description' => null,
                'start_at' => '2023-11-04 10:30',
                'finish_at' => '2023-11-04 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '390',
                'program_id' => 52,
                'speaker_id' => null,
                'code' => 'S-39',
                'title' => 'Nivolumab Ile Tedavi Edilen Renal Hücreli Karsinom Hastalarında Eş Zamanlı Proton Pompa Inhibitörlerinin Sağkalım Sonuçları Üzerindeki Etkisi',
                'description' => null,
                'start_at' => '2023-11-04 10:30',
                'finish_at' => '2023-11-04 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '400',
                'program_id' => 52,
                'speaker_id' => null,
                'code' => 'S-40',
                'title' => 'Nivolumab Tedavisi Alan Renal Hücreli Kanser Hastalarında Gfr Düşüklüğünün Tedavi Yanıtı Üzerindeki Etkileri',
                'description' => null,
                'start_at' => '2023-11-04 10:30',
                'finish_at' => '2023-11-04 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '410',
                'program_id' => 52,
                'speaker_id' => null,
                'code' => 'S-41',
                'title' => 'Nivolumab Tedavisi Alan Metastatik Renal Hücreli Karsinom Tanılı Hastalarda Prognostik Marker Olarak Gustave Roussy Immun Skoru',
                'description' => null,
                'start_at' => '2023-11-04 10:30',
                'finish_at' => '2023-11-04 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '420',
                'program_id' => 52,
                'speaker_id' => null,
                'code' => 'S-42',
                'title' => '70 Yaş Üzeri Metastatik Mesane Kanserli Hastalarda Gnri, Conut, Pni’nin Prognoza Etkisi',
                'description' => null,
                'start_at' => '2023-11-04 10:30',
                'finish_at' => '2023-11-04 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '430',
                'program_id' => 52,
                'speaker_id' => null,
                'code' => 'S-43',
                'title' => 'Nivolumab Ile Tedavi Edilen Böbrek Kanseri Ve Malign Melanomlu Hastalar Için Imdc Risk Skorunun Prognostik Değerinin Değerlendirilmesi',
                'description' => null,
                'start_at' => '2023-11-04 10:30',
                'finish_at' => '2023-11-04 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '440',
                'program_id' => 52,
                'speaker_id' => null,
                'code' => 'S-44',
                'title' => 'Yüksek Derecede Emetojenik Tedavi Alan Kemonaif Hastalarda Kemoterapiye Bağlı Gelişen Bulantı Ve Kusmanın Önlenmesinde Aprepitant Ve Fosaprepitantın Karşılaştırılması',
                'description' => null,
                'start_at' => '2023-11-04 10:30',
                'finish_at' => '2023-11-04 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '450',
                'program_id' => 52,
                'speaker_id' => null,
                'code' => 'S-45',
                'title' => 'Opioid Analjeziklerin İmmün Kontrol Noktası İnhibitörleri Kullanan Kanser Hastalarında Sağkalıma Etkisi ',
                'description' => null,
                'start_at' => '2023-11-04 10:30',
                'finish_at' => '2023-11-04 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '460',
                'program_id' => 52,
                'speaker_id' => null,
                'code' => 'S-46',
                'title' => 'İmmünoterapi Alan Solid Tümör Hastalarında Charlson Komorbidite Indeksinin Immünoterapi Ilişkili Yan Etkileri Öngörmedeki Etkinliğinin Değerlendirilmesi',
                'description' => null,
                'start_at' => '2023-11-04 10:30',
                'finish_at' => '2023-11-04 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '470',
                'program_id' => 52,
                'speaker_id' => null,
                'code' => 'S-47',
                'title' => 'Nötrofil/eozinofil Oranı (Ner), Lenfosit/eozinofil Oranı (Ler) Immün Kontrol Nokta Inhibitör Tedavisi Ilişkili Yan Etkiyi Predikte Edebilir Mi?',
                'description' => null,
                'start_at' => '2023-11-04 10:30',
                'finish_at' => '2023-11-04 12:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 53,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Vakalarla Meme Kanserine Yaklaşım',
                'description' => 'Panelistler/Tartışmacılar: Nail Paksoy, Osman Sütçüoğlu, Elif Şenocak Taşcı',
                'start_at' => '2023-12-16 10:00',
                'finish_at' => '2023-12-16 11:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 53,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Pratikte Aklımıza Gelen Sorular',
                'description' => 'Panelistler/Tartışmacılar: Gözde Kavgacı, Berkan Karadurmuş, Eda Erçin, Hakan Demir, Süleyman Can',
                'start_at' => '2023-12-16 11:00',
                'finish_at' => '2023-12-16 12:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 55,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Vakalarla Akciğer Kanserine Yaklaşım',
                'description' => 'Panelistler/Tartışmacılar: Serdar Karakaya, Deniz Can Güven, Seval Ay',
                'start_at' => '2023-12-16 13:30',
                'finish_at' => '2023-12-16 14:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 55,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Pratikte Aklımıza Gelen Sorular',
                'description' => 'Panelistler/Tartışmacılar: Ahmet Ünsal, Ayşe Tan Doğruel, Duygu Ercan Uzundal, Elif Eker, Görkem Turhan',
                'start_at' => '2023-12-16 14:30',
                'finish_at' => '2023-12-16 15:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 57,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Vakalarla Melanoma Yaklaşım',
                'description' => 'Panelistler/Tartışmacılar: Özgecan Dülgar, Barış Aykan, Ali Oğul',
                'start_at' => '2023-12-16 16:00',
                'finish_at' => '2023-12-16 17:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 57,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Pratikte Aklımıza Gelen Sorular',
                'description' => 'Panelistler/Tartışmacılar: Alper Yaşar, Arif Akyıldız, Doğukan Saydan, Bengü Dursun, Oğuzcan Kınıkoğlu',
                'start_at' => '2023-12-16 17:00',
                'finish_at' => '2023-12-16 18:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 58,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Vakalarla Genitoüriner Kanserlere Yaklaşım',
                'description' => 'Panelistler/Tartışmacılar: Burak Bilgin, Ersin Özaslan, Nilay Şengül Samancı',
                'start_at' => '2023-12-17 10:00',
                'finish_at' => '2023-12-17 11:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 58,
                'speaker_id' => null,
                'code' => null,
                'title' => 'Pratikte Aklımıza Gelen Sorular',
                'description' => 'Panelistler/Tartışmacılar: Furkan Ceylan, Mustafa Seyyar, Pınar Açar, İlknur Deliktaş Onur, Esra Asarkaya',
                'start_at' => '2023-12-17 11:00',
                'finish_at' => '2023-12-17 12:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
        ]);
    }
}
