<?php

namespace Database\Seeders;

use App\Models\Meeting\Hall\Program\Session\Session;
use Illuminate\Database\Seeder;

class MeetingHallProgramSessionSeeder extends Seeder
{
    public function run(): void
    {
        Session::insert([
           [
                'sort_order' => '10',
                'program_id' => 2,
                'speaker_id' => 3,
                'code' => 'panel-1-1',
                'title' => 'EGFR Mutasyonu Olan Küçük Hücreli Dışı Akciğer Kanserinde Tedavi Yaklaşımı',
                'start_at' => '2022-10-22 09:15',
                'finish_at' => '2022-10-22 09:35',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 2,
                'speaker_id' => 4,
                'code' => 'panel-1-2',
                'title' => 'KRAS, MET, RET, HER2, BRAF Mutasyonu Olan Hastalarda Tedavi',
                'start_at' => '2022-10-22 09:35',
                'finish_at' => '2022-10-22 09:55',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 2,
                'speaker_id' => 5,
                'code' => 'panel-1-3',
                'title' => 'Mutasyon Saptanmayan Küçük Hücreli Dışı Akciğer Kanserinde Tedavi',
                'start_at' => '2022-10-22 09:55',
                'finish_at' => '2022-10-22 10:15',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 2,
                'speaker_id' => 6,
                'code' => 'panel-1-4',
                'title' => 'Beyin Metastazı Olan Küçük Hücreli Dışı Akciğer Kanseri Hastalarında Tedavi Yaklaşımı',
                'start_at' => '2022-10-22 10:15',
                'finish_at' => '2022-10-22 10:35',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 2,
                'speaker_id' => 7,
                'code' => 'panel-1-4',
                'title' => 'Soru & Cevap & Tartışma',
                'start_at' => '2022-10-22 10:35',
                'finish_at' => '2022-10-22 11:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 4,
                'speaker_id' => 8,
                'code' => 'S-01',
                'title' => 'Sınırlı Evre Küçük Hücreli Akciğer Kanserinde Sistemik Enflamasyon Yanıt İndeksi İle Prognoz Arası İlişki',
                'start_at' => '2022-10-20 11:20',
                'finish_at' => '2022-10-20 12:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 4,
                'speaker_id' => 9,
                'code' => 'S-38',
                'title' => 'Safra Kesesi Ve Safra Yolları Kanserinde Adjuvan Tedavide Gemsitabin İle Kapesitabinin Karşılaştırılması, Tek Merkez Deneyimi',
                'start_at' => '2022-10-20 11:20',
                'finish_at' => '2022-10-20 12:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 4,
                'speaker_id' => 10,
                'code' => 'S-03',
                'title' => 'Opere Edilmiş Evre III Akciğer Kanseri Hastalarında İnflamatuar Prognostik Belirteçler',
                'start_at' => '2022-10-20 11:20',
                'finish_at' => '2022-10-20 12:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 4,
                'speaker_id' => 1,
                'code' => 'S-04',
                'title' => 'Lokal İleri Veya Metastatik KHDAK Olan Hastalarda Nivolumabın Etkinlik Ve Güvenliliğini Değerlendiren Retrospektif Bir Çalışma',
                'start_at' => '2022-10-20 11:20',
                'finish_at' => '2022-10-20 12:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 4,
                'speaker_id' => 6,
                'code' => 'S-05',
                'title' => 'KRAS-G12C Mutant Metastatik Küçük Hücreli Dışı Akciğer Kanseri Hastalarında İmmünoterapi İle Sağkalım Sonuçlarının Değerlendirilmesi',
                'start_at' => '2022-10-20 11:20',
                'finish_at' => '2022-10-20 12:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '60',
                'program_id' => 4,
                'speaker_id' => 6,
                'code' => 'S-06',
                'title' => 'Nivolumab Tedavisi Alan Metastatik Küçük Hücreli Dışı Akciğer Kanserli Hastaların Klinik Özellikleri Ve Sağkalım Sonuçları; Tek Merkez Deneyimi',
                'start_at' => '2022-10-20 11:20',
                'finish_at' => '2022-10-20 12:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '70',
                'program_id' => 4,
                'speaker_id' => 6,
                'code' => 'S-07',
                'title' => 'Küçük Hücreli Akciğer Kanserinde Kemoterapinin Etkinliği: İkinci Basamak Ve Ötesi',
                'start_at' => '2022-10-20 11:20',
                'finish_at' => '2022-10-20 12:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '80',
                'program_id' => 4,
                'speaker_id' => 6,
                'code' => 'S-08',
                'title' => 'Toraks BT Çekimlerinde Akciğerde Rastlantısal Nodül Sıklığı',
                'start_at' => '2022-10-20 11:20',
                'finish_at' => '2022-10-20 12:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 7,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Baş Boyun Kanserinde İmmünoterapi',
                'start_at' => '2022-10-20 14:00',
                'finish_at' => '2022-10-20 14:20',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 7,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Metastatik Melanomda Yeni Tedavi Seçenekleri',
                'start_at' => '2022-10-20 14:20',
                'finish_at' => '2022-10-20 14:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 7,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'İmatinibe Resistant Gastrointestinal Stromal Tümörlerde Tedavi Seçenekleri',
                'start_at' => '2022-10-20 14:40',
                'finish_at' => '2022-10-20 15:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 7,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Sarkomlarda Alt Tiplere Göre Sistemik Tedaviler',
                'start_at' => '2022-10-20 15:00',
                'finish_at' => '2022-10-20 15:20',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 7,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Soru & Cevap & Tartışma',
                'start_at' => '2022-10-20 15:20',
                'finish_at' => '2022-10-20 15:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 10,
                'speaker_id' => 6,
                'code' => 'S-09',
                'title' => 'Erişkin Medulloblastomda Tedavi Yaklaşımlarının Rolü Ve Uzun Dönem Sonuçları: Tek Merkez Deneyimi',
                'start_at' => '2022-10-20 16:30',
                'finish_at' => '2022-10-20 17:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 10,
                'speaker_id' => 6,
                'code' => 'S-10',
                'title' => 'Relaps Veya Refrakter Medulloblastomlu Erişkin Hastalarda Yüksek Doz Kemoterapinin Etkinliği',
                'start_at' => '2022-10-20 16:30',
                'finish_at' => '2022-10-20 17:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 10,
                'speaker_id' => 6,
                'code' => 'S-11',
                'title' => 'Lokal İleri Nazofarenks Kanserli Hastalarda İndüksiyon Kemoterapisinin Konsolidasyon Kemoterapisi İle Karşılaştırılması: Hangi Hastaya; Kaç Kür ?',
                'start_at' => '2022-10-20 16:30',
                'finish_at' => '2022-10-20 17:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 10,
                'speaker_id' => 6,
                'code' => 'S-12',
                'title' => 'Nivolumab Tedavisi Alan Malign Melanom Hastalarında Pan-İmmun-İnflammation Value (PIV) İle Genel Sağ Kalım İlişkisi; Tek Merkez Deneyimi',
                'start_at' => '2022-10-20 16:30',
                'finish_at' => '2022-10-20 17:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 10,
                'speaker_id' => 6,
                'code' => 'S-13',
                'title' => 'Nivolumab Tedavisi Alan Malign Melanom Hastalarında Prognostik Nutrisyonel İndex(PNI) İle Genel Sağkalım İlişkisi-Tek Merkez Deneyimi',
                'start_at' => '2022-10-20 16:30',
                'finish_at' => '2022-10-20 17:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '60',
                'program_id' => 10,
                'speaker_id' => 6,
                'code' => 'S-14',
                'title' => 'Osteosarkom Sa-Os Hücre Hattında CDK 4/6 İnhibitörü Ribosiklibin Kemoduyarlılaştırma Etkinliğinin Değerlendirilmesi',
                'start_at' => '2022-10-20 16:30',
                'finish_at' => '2022-10-20 17:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '70',
                'program_id' => 10,
                'speaker_id' => 6,
                'code' => 'S-15',
                'title' => 'Nivolumab Kullanan Hastalarda Nütrisyonel Durum Değerlendirmesi',
                'start_at' => '2022-10-20 16:30',
                'finish_at' => '2022-10-20 17:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '80',
                'program_id' => 10,
                'speaker_id' => 6,
                'code' => 'S-16',
                'title' => 'Anti PD-1 Monoklonal Antikorlara Bağlı Hipofizit: Tek Merkez Deneyimi',
                'start_at' => '2022-10-20 16:30',
                'finish_at' => '2022-10-20 17:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '90',
                'program_id' => 10,
                'speaker_id' => 6,
                'code' => 'S-17',
                'title' => 'Küçük Hücreli Dışı Akciğer Kanserinde Tedavi Öncesi Bakılan Prognostik Nutrisyonel İndeks İle Nivolumab Tedavisi Arasında Olabilecek İlişkinin Retrospektif Araştırılması',
                'start_at' => '2022-10-20 16:30',
                'finish_at' => '2022-10-20 17:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 12,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Metastatik Kastrasyona Duyarlı Prostat Kanseri Tedavisi',
                'start_at' => '2022-10-21 09:00',
                'finish_at' => '2022-10-21 09:20',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 12,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Non-Metastatik Kasa İnvaze Mesane Kanserinde Optimal Tedavi',
                'start_at' => '2022-10-21 09:20',
                'finish_at' => '2022-10-21 09:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 12,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Metastatik Renal Hücreli Kanserin Tedavisinde Yenilikler Ve Sağkalımın Belirleyicileri',
                'start_at' => '2022-10-21 09:40',
                'finish_at' => '2022-10-21 10:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 12,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Soru & Cevap & Tartışma',
                'start_at' => '2022-10-21 10:00',
                'finish_at' => '2022-10-21 10:20',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 15,
                'speaker_id' => 6,
                'code' => 'S-18',
                'title' => 'Yüksek Doz Kemoterapi Ve Otolog Kök Hücre Nakli Uygulanan Relaps Veya Refrakter Erkek Germ Hücreli Tümör Olgularının Retrospektif İncelemesi',
                'start_at' => '2022-10-21 11:10',
                'finish_at' => '2022-10-21 11:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 15,
                'speaker_id' => 6,
                'code' => 'S-19',
                'title' => 'Metastatik Renal Hücreli Karsinomda Birinci Basamak Tedavi Öncesi HALP (Hemoglobin-Albümin-Lenfosit-Platelet) Skoru İle Metastatik Genel Sağ Kalım Arasındaki İlişkinin Değerlendirilmesi',
                'start_at' => '2022-10-21 11:10',
                'finish_at' => '2022-10-21 11:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 15,
                'speaker_id' => 6,
                'code' => 'S-20',
                'title' => 'Metastatik Hormon Duyarlı Prostat Karsinomu’nda Prognozu Öngörmede CHAARTED Ve LATITUDE Kriterlerinin Karşılaştırılması',
                'start_at' => '2022-10-21 11:10',
                'finish_at' => '2022-10-21 11:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 15,
                'speaker_id' => 6,
                'code' => 'S-21',
                'title' => 'Böbrek Şeffaf Hücreli Kanser Tanılı Nivolumab İle Tedavi Edilen Hastalarda Tedavi Yanıtını Ön Gördürücü Bir Model; Modifiye Glasgow Prognostik Skoru',
                'start_at' => '2022-10-21 11:10',
                'finish_at' => '2022-10-21 11:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 15,
                'speaker_id' => 6,
                'code' => 'S-22',
                'title' => 'Geriatrik Onkoloji Hastalarında Depresyon Ve İlişkili Faktörler: Tek Merkez Deneyimi',
                'start_at' => '2022-10-21 11:10',
                'finish_at' => '2022-10-21 11:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '60',
                'program_id' => 15,
                'speaker_id' => 6,
                'code' => 'S-23',
                'title' => 'Koronavirüs-19 Pandemi Sürecinin Kanser Hastaları Üzerindeki Psikolojik Etkilerinin Değerlendirilmesi',
                'start_at' => '2022-10-21 11:10',
                'finish_at' => '2022-10-21 11:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '70',
                'program_id' => 15,
                'speaker_id' => 6,
                'code' => 'S-24',
                'title' => 'Solid Organ Maligniteli Hastalarda Pet Suvmax Değerleri Ve Ebus Biyopsi Sonuçlarının Karşılaştırmalı Değerlendirilmesi',
                'start_at' => '2022-10-21 11:10',
                'finish_at' => '2022-10-21 11:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '80',
                'program_id' => 15,
                'speaker_id' => 6,
                'code' => 'S-25',
                'title' => 'Gastrointestinal Tümöre Yönelik Kemoterapi Alan Hastalarda Sarkopeni Düzeyinin Uzaktan Malnutrisyon-Sarkopeni Uygulaması İle Korelasyonu',
                'start_at' => '2022-10-21 11:10',
                'finish_at' => '2022-10-21 11:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '90',
                'program_id' => 15,
                'speaker_id' => 6,
                'code' => 'S-26',
                'title' => 'Solid Kanser Tanısı Olan Hastalarda B12/CRP Oranının (BCO) Prognostik Değeri',
                'start_at' => '2022-10-21 11:10',
                'finish_at' => '2022-10-21 11:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 18,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Hormon Pozitif Metastatik Meme Kanserinde Birinci Basamak Tedavi ve Ötesi',
                'start_at' => '2022-10-21 13:30',
                'finish_at' => '2022-10-21 13:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 18,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Meme Kanseri Tedavisinde İmmünoterapi',
                'start_at' => '2022-10-21 13:50',
                'finish_at' => '2022-10-21 14:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 18,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'HER2(+) Metastatik Meme Kanserinde Yeni Tedavi Seçenekleri',
                'start_at' => '2022-10-21 14:10',
                'finish_at' => '2022-10-21 14:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 18,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Memenin Nadir Tümörlerinde Tedavi',
                'start_at' => '2022-10-21 14:30',
                'finish_at' => '2022-10-21 14:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 18,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Soru & Cevap & Tartışma',
                'start_at' => '2022-10-21 14:50',
                'finish_at' => '2022-10-21 15:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 21,
                'speaker_id' => 6,
                'code' => 'S-27',
                'title' => 'Üçlü Negatif Meme Kanseri (Ünmk) Hücre Hatlarındaki CD44/CD24 Belirtecini Farklı Düzeylerde Taşıyan Alt-Grupların Monosit/Makrofaj Aracılı T Hücre Yanıtlarına Etkisi',
                'start_at' => '2022-10-21 16:00',
                'finish_at' => '2022-10-21 16:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 21,
                'speaker_id' => 6,
                'code' => 'S-28',
                'title' => 'Metastatik Luminal A Tip Meme Kanserinde CDK4/6 İnhibitör Tedavi Etkinliğine Wip1 Fosfotaz Ve İnhibitörlerinin Etkisinin Araştırılması',
                'start_at' => '2022-10-21 16:00',
                'finish_at' => '2022-10-21 16:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 21,
                'speaker_id' => 6,
                'code' => 'S-29',
                'title' => 'Kemoterapi Alan Meme Kanseri Hastalarında Depresyon Durumu Ve Uyku Kalitesinin Değerlendirilmesi',
                'start_at' => '2022-10-21 16:00',
                'finish_at' => '2022-10-21 16:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 21,
                'speaker_id' => 6,
                'code' => 'S-30',
                'title' => 'Her2-Pozitif Meme Kanserinde Biyobenzer Trastuzumab MYL-1401Onun Etkinlik Ve Güvenlik Değerlendirmesi',
                'start_at' => '2022-10-21 16:00',
                'finish_at' => '2022-10-21 16:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 21,
                'speaker_id' => 6,
                'code' => 'S-31',
                'title' => 'Akut Faz Parametreleri, Hormon Pozitif Metastatik Meme Kanserinde CDK 4/6 İnhibitörlerine Yanıtı Predikte Eder Mi?',
                'start_at' => '2022-10-21 16:00',
                'finish_at' => '2022-10-21 16:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '60',
                'program_id' => 21,
                'speaker_id' => 6,
                'code' => 'S-32',
                'title' => 'TDM-1 İle Tedavi Edilen Her2/Neu Pozitif Metastatik Meme Kanseri Tanılı Hastalarda Tedavi Zamanlaması Ve Klinik Özelliklerle Sağkalım Parametrelerinin Arasındaki İlişkinin İncelenmesi',
                'start_at' => '2022-10-21 16:00',
                'finish_at' => '2022-10-21 16:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '70',
                'program_id' => 21,
                'speaker_id' => 6,
                'code' => 'S-33',
                'title' => 'Meme Kanserinde Her-2 Diskordansı: Tek Merkez Deneyimi',
                'start_at' => '2022-10-21 16:00',
                'finish_at' => '2022-10-21 16:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '80',
                'program_id' => 21,
                'speaker_id' => 6,
                'code' => 'S-34',
                'title' => 'Premenapozal Endokrin Duyarlı Metastatik Meme Kanserli Hastalarda Ribosiklib Ve Palbosiklibin Karşılaştırılması',
                'start_at' => '2022-10-21 16:00',
                'finish_at' => '2022-10-21 16:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 24,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Onkolojide HİPEC’in Rasyonel Kullanımı',
                'start_at' => '2022-10-22 09:00',
                'finish_at' => '2022-10-22 09:20',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 24,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'İleri Evre Endometrium Kanseri Tedavisinde Yeni Tedavi Seçenekleri',
                'start_at' => '2022-10-22 09:20',
                'finish_at' => '2022-10-22 09:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 24,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Over Kanserinde İdame Tedavi ve Platin Dirençli Hastalıkta Güncel Gelişmeler',
                'start_at' => '2022-10-22 09:40',
                'finish_at' => '2022-10-22 10:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 24,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Soru & Cevap & Tartışma',
                'start_at' => '2022-10-22 10:00',
                'finish_at' => '2022-10-22 10:20',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 27,
                'speaker_id' => 6,
                'code' => 'S-35',
                'title' => 'Opere 70 Yaş Üstündeki Kolanjiosellüler Kanser Hastalarında Adjuvan Kapesitabin Kullanımı: Tek Merkez Deneyimi',
                'start_at' => '2022-10-22 10:50',
                'finish_at' => '2022-10-22 11:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 27,
                'speaker_id' => 6,
                'code' => 'S-36',
                'title' => 'Metastatik Mide Kanserli Hastalarda Tedavi Öncesi Bakılan Sistemik İmmün İnflamasyon İndeksi Ve Panimmun İnflamasyon İndeksi’nin Klinik Önemi',
                'start_at' => '2022-10-22 10:50',
                'finish_at' => '2022-10-22 11:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 27,
                'speaker_id' => 6,
                'code' => 'S-37',
                'title' => 'Metastatik Pankreas Kanseri Tanılı Hastalarda Yaş Tedavi Tercihimizi Etkilemeli Mi?',
                'start_at' => '2022-10-22 10:50',
                'finish_at' => '2022-10-22 11:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 27,
                'speaker_id' => 6,
                'code' => 'S-38',
                'title' => 'İleri Akciğer Kanseri İnflamasyon İndeksi (ALI), Nivolumab Tedavisi Uygulanan Metastatik Küçük Hücreli Dışı Akciğer Kanserli Hastalarda Prognozu Belirlemede Yol Gösterici Midir?',
                'start_at' => '2022-10-22 10:50',
                'finish_at' => '2022-10-22 11:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 27,
                'speaker_id' => 6,
                'code' => 'S-39',
                'title' => 'Metastatik Pankreas Kanserli Hastalarda İkinci Basamak Tedavi Sonuçları',
                'start_at' => '2022-10-22 10:50',
                'finish_at' => '2022-10-22 11:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '60',
                'program_id' => 27,
                'speaker_id' => 6,
                'code' => 'S-40',
                'title' => 'Metastatik Ve Nonmetastatik Kolon Kanserinde Peritümöral Ve İntratümöral Tümör İnfiltre Lenfosit Farklılıkları',
                'start_at' => '2022-10-22 10:50',
                'finish_at' => '2022-10-22 11:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '70',
                'program_id' => 27,
                'speaker_id' => 6,
                'code' => 'S-41',
                'title' => 'Grade 3 Gastroenteropankreatik Nöroendokrin Neoplazmlarda Farklı Özellikler Ve Yaşam Süreleri',
                'start_at' => '2022-10-22 10:50',
                'finish_at' => '2022-10-22 11:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '80',
                'program_id' => 27,
                'speaker_id' => 6,
                'code' => 'S-42',
                'title' => 'Gastrik Ve Gastroözefageal Kanserlerde CD74 Overekspresyonunun Klinik Parametreler Ve Prognozla İlişkisi Var Mıdır?',
                'start_at' => '2022-10-22 10:50',
                'finish_at' => '2022-10-22 11:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '90',
                'program_id' => 27,
                'speaker_id' => 6,
                'code' => 'S-43',
                'title' => 'Metastatik Pankreas Kanserli Hastalarda Albi Skoru İle Sağkalım Arasındaki İlişki',
                'start_at' => '2022-10-22 10:50',
                'finish_at' => '2022-10-22 11:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '100',
                'program_id' => 27,
                'speaker_id' => 6,
                'code' => 'S-44',
                'title' => '75 Yaş Üstü Kolorektal Kanserli Hastalarda Tedavi Sonuçları',
                'start_at' => '2022-10-22 10:50',
                'finish_at' => '2022-10-22 11:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 30,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Kolorektal Kanserlerde Yeni Hedefler ve Tedaviler',
                'start_at' => '2022-10-22 13:30',
                'finish_at' => '2022-10-22 13:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 30,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Metastatik Mide Kanserinde Güncel Tedavi Yaklaşımı',
                'start_at' => '2022-10-22 13:50',
                'finish_at' => '2022-10-22 14:10',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 30,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'İleri Evre Hepatoselüler Kanser Tedavisinde İmmünoterapide ve Hedefe Yönelik Tedavilerde Gelişmeler',
                'start_at' => '2022-10-22 14:10',
                'finish_at' => '2022-10-22 14:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 30,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Soru & Cevap & Tartışma',
                'start_at' => '2022-10-22 14:30',
                'finish_at' => '2022-10-22 14:50',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 33,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'NGS – Hangi Hastaya ve Ne Zaman ?',
                'start_at' => '2022-10-22 15:40',
                'finish_at' => '2022-10-22 16:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '60',
                'program_id' => 33,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'MSI, PDL-1, TMB: Hangi Hastada, Ne Zaman ve Hangi Tedavi ?',
                'start_at' => '2022-10-22 16:00',
                'finish_at' => '2022-10-22 16:20',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '70',
                'program_id' => 33,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'BRCA, HRD Hangi Hastada, Ne Zaman ve Hangi Tedavi?',
                'start_at' => '2022-10-22 16:20',
                'finish_at' => '2022-10-22 16:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '80',
                'program_id' => 33,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Yenilikçi İlaçlara Erişim ve Bütçe Etkisi',
                'start_at' => '2022-10-22 16:40',
                'finish_at' => '2022-10-22 17:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '90',
                'program_id' => 33,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Soru & Cevap & Tartışma',
                'start_at' => '2022-10-22 17:00',
                'finish_at' => '2022-10-22 17:20',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '10',
                'program_id' => 35,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Kanser ve Kaşeksi',
                'start_at' => '2022-10-23 09:00',
                'finish_at' => '2022-10-23 09:20',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '20',
                'program_id' => 35,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Kanser ve Tromboz',
                'start_at' => '2022-10-23 09:20',
                'finish_at' => '2022-10-23 09:40',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '30',
                'program_id' => 35,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Kanserde Ağrı Tedavisi',
                'start_at' => '2022-10-23 09:40',
                'finish_at' => '2022-10-23 10:00',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '40',
                'program_id' => 35,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Kanserli Hastalarda Psikolojik Destek',
                'start_at' => '2022-10-23 10:00',
                'finish_at' => '2022-10-23 10:20',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
            [
                'sort_order' => '50',
                'program_id' => 35,
                'speaker_id' => 6,
                'code' => null,
                'title' => 'Soru & Cevap & Tartışma',
                'start_at' => '2022-10-23 10:20',
                'finish_at' => '2022-10-23 10:30',
                'on_air' => 0,
                'questions_limit' => 3,
                'questions_allowed' => 0,
                'questions_auto_start' => 0,
                'is_questions_started' => 0,
                'status' => 1,
            ],
        ]);
    }
}
