<?php

namespace Database\Seeders;

use App\Models\Meeting\Hall\Program\Program;
use Illuminate\Database\Seeder;

class MeetingHallProgramSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Program::insert([
            [
                'hall_id' => '5',
                'sort_order' => '10',
                'code' => null,
                'title' => 'Açılış Töreni',
                'description' => 'Başak Oyan Uluç',
                'start_at' => '2022-10-20 09:00',
                'finish_at' => '2022-10-20 09:15',
                'type' => 'other',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '20',
                'code' => 'panel-1',
                'title' => 'Panel 1',
                'description' => null,
                'start_at' => '2022-10-20 09:15',
                'finish_at' => '2022-10-20 11:00',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '30',
                'code' => null,
                'title' => 'Kahve Molası',
                'description' => null,
                'start_at' => '2022-10-20 11:00',
                'finish_at' => '2022-10-20 11:20',
                'type' => 'other',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '40',
                'code' => 'sozel-bildiriler-1',
                'title' => 'Sözel Bildiriler 1',
                'description' => null,
                'start_at' => '2022-10-20 11:20',
                'finish_at' => '2022-10-20 12:00',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '50',
                'code' => 'takeda-uydu-sempozyumu',
                'title' => 'Takeda Uydu Sempozyumu',
                'description' => null,
                'start_at' => '2022-10-20 12:00',
                'finish_at' => '2022-10-20 12:30',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '60',
                'code' => null,
                'title' => 'Öğle Yemeği',
                'description' => null,
                'start_at' => '2022-10-22 12:30',
                'finish_at' => '2022-10-22 14:00',
                'type' => 'other',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '70',
                'code' => 'panel-2',
                'title' => 'Panel 2',
                'description' => null,
                'start_at' => '2022-10-20 14:00',
                'finish_at' => '2022-10-20 15:40',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '80',
                'code' => null,
                'title' => 'Kahve Molası',
                'description' => null,
                'start_at' => '2022-10-20 15:40',
                'finish_at' => '2022-10-20 16:00',
                'type' => 'other',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '90',
                'code' => 'novartis-uydu-sempozyumu',
                'title' => 'Novartis Uydu Sempozyumu',
                'description' => null,
                'start_at' => '2022-10-22 16:00',
                'finish_at' => '2022-10-22 16:30',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '100',
                'code' => 'sozel-bildiriler-2',
                'title' => 'Sözel Bildiriler 2',
                'description' => null,
                'start_at' => '2022-10-20 16:30',
                'finish_at' => '2022-10-20 17:10',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '110',
                'code' => 'debate',
                'title' => 'Debate',
                'description' => null,
                'start_at' => '2022-10-20 17:10',
                'finish_at' => '2022-10-20 18:40',
                'type' => 'debate',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '10',
                'code' => 'panel-3',
                'title' => 'PANEL 3',
                'description' => 'Oturum Başkanları: Mehmet Bilici, Güzin Demirağ, Aziz Karaoğlu',
                'start_at' => '2022-10-21 09:00',
                'finish_at' => '2022-10-21 10:20',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '20',
                'code' => 'gen-uydu-sempozyumu',
                'title' => 'Gen Uydu Sempozyumu',
                'description' => 'Metastatik RCC Tedavisinde Güncel Gelişmeler ve Kabozantinibin Yeri',
                'start_at' => '2022-10-21 10:20',
                'finish_at' => '2022-10-21 10:50',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '30',
                'code' => null,
                'title' => 'Kahve Molası',
                'description' => null,
                'start_at' => '2022-10-21 10:50',
                'finish_at' => '2022-10-21 11:10',
                'type' => 'other',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '40',
                'code' => 'sozel-bildiriler-3',
                'title' => 'Sözel Bildiriler 3',
                'description' => null,
                'start_at' => '2022-10-22 11:10',
                'finish_at' => '2022-10-22 11:50',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '50',
                'code' => 'astellas-uydu-sempozyumu',
                'title' => 'Astellas Uydu Sempozyumu',
                'description' => 'Xtandi’yle Prostat Kanserinde Zamanın Ötesinde',
                'start_at' => '2022-10-21 11:50',
                'finish_at' => '2022-10-21 12:20',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '60',
                'code' => null,
                'title' => 'Öğle Yemeği',
                'description' => null,
                'start_at' => '2022-10-21 12:30',
                'finish_at' => '2022-10-21 13:30',
                'type' => 'other',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '70',
                'code' => 'panel-4',
                'title' => 'Panel 4',
                'description' => null,
                'start_at' => '2022-10-21 13:30',
                'finish_at' => '2022-10-21 15:10',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '80',
                'code' => null,
                'title' => 'Kahve Molası',
                'description' => null,
                'start_at' => '2022-10-22 15:10',
                'finish_at' => '2022-10-22 15:30',
                'type' => 'other',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '90',
                'code' => 'farmanova-uydu-sempozyumu',
                'title' => 'Farmanova Uydu Sempozyumu',
                'description' => 'HR+ HER2- İleri Evre Meme Kanserine Klinik ve Moleküler Bakış: Sorularla Valamor ve Pimreva',
                'start_at' => '2022-10-21 15:30',
                'finish_at' => '2022-10-21 16:00',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '100',
                'code' => 'sozel-bildiriler-4',
                'title' => 'Sözel Bildiriler 4',
                'description' => null,
                'start_at' => '2022-10-21 16:00',
                'finish_at' => '2022-10-21 16:40',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '110',
                'code' => 'debate',
                'title' => 'Debate',
                'description' => 'ÖZEFAGOGASTRİK BİLEŞKE TÜMÖRLERİNDE NEOADJUVAN KT VS. KRT?',
                'start_at' => '2022-10-21 16:40',
                'finish_at' => '2022-10-21 18:10',
                'type' => 'debate',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '10',
                'code' => null,
                'title' => 'Akılcı İlaç Kullanımı',
                'description' => 'Oturum Başkanı: Gökhan Çelenkoğlu',
                'start_at' => '2022-10-22 08:40',
                'finish_at' => '2022-10-22 09:00',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '20',
                'code' => 'panel-5',
                'title' => 'PANEL 5',
                'description' => 'Oturum Başkanları: Pınar Saip, Salim Başol Tekin',
                'start_at' => '2022-10-22 09:00',
                'finish_at' => '2022-10-22 10:20',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '30',
                'code' => 'gsk-uydu-sempozyumu',
                'title' => 'GSK Uydu Sempozyumu',
                'description' => 'Over Kanseri İdame Tedavisinde Zejula ile Yeni Bir Dönem',
                'start_at' => '2022-10-22 10:20',
                'finish_at' => '2022-10-22 10:50',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '40',
                'code' => null,
                'title' => 'Kahve Molası',
                'description' => null,
                'start_at' => '2022-10-22 10:50',
                'finish_at' => '2022-10-22 11:10',
                'type' => 'other',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '50',
                'code' => 'sozel-bildiriler-5',
                'title' => 'Sözel Bildiriler 5',
                'description' => 'Oturum Başkanları: Murat Araz, Didem Şener, Ali Murat Sedef',
                'start_at' => '2022-10-22 11:10',
                'finish_at' => '2022-10-22 11:50',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '60',
                'code' => 'bristol-uydu-sempozyumu',
                'title' => 'Bristol Uydu Sempozyumu',
                'description' => '1. Basamak Renal Hücreli Karsinom Tedavisinde İmmünoterapi Deneyimi : Nivolumab + İpilimumab',
                'start_at' => '2022-10-22 11:50',
                'finish_at' => '2022-10-22 12:20',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '70',
                'code' => null,
                'title' => 'Öğle Yemeği',
                'description' => null,
                'start_at' => '2022-10-22 12:30',
                'finish_at' => '2022-10-22 13:30',
                'type' => 'other',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '80',
                'code' => 'panel-6',
                'title' => 'Panel 6',
                'description' => null,
                'start_at' => '2022-10-22 13:30',
                'finish_at' => '2022-10-22 14:50',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '90',
                'code' => null,
                'title' => 'Kahve Molası',
                'description' => null,
                'start_at' => '2022-10-22 14:50',
                'finish_at' => '2022-10-22 15:10',
                'type' => 'other',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '100',
                'code' => 'msd-uydu-sempozyumu',
                'title' => 'MSD Uydu Sempozyumu',
                'description' => 'Metastatik Küçük Hücreli Dışı Akciğer Kanserinin 1.Basamak Tedavisinde Güncel Gelişmeler',
                'start_at' => '2022-10-22 15:10',
                'finish_at' => '2022-10-22 15:55',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '110',
                'code' => 'panel-7',
                'title' => 'PANEL 7',
                'description' => null,
                'start_at' => '2022-10-22 15:40',
                'finish_at' => '2022-10-22 17:20',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '120',
                'code' => 'kapanis',
                'title' => 'KAPANIŞ',
                'description' => null,
                'start_at' => '2022-10-22 17:20',
                'finish_at' => '2022-10-22 18:00',
                'type' => 'other',
                'is_started' => '0',
                'status' => 1,
            ],
            [
                'hall_id' => '5',
                'sort_order' => '10',
                'code' => null,
                'title' => 'PALYATİF TEDAVİLER KURSU',
                'description' => null,
                'start_at' => '2022-10-23 09:00',
                'finish_at' => '2022-10-23 10:30',
                'type' => 'session',
                'is_started' => '0',
                'status' => 1,
            ]
        ]);
    }
}
