<?php

namespace Database\Seeders;

use App\Models\Meeting\Participant\Participant;
use Faker\Factory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MeetingParticipantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $faker1 = Factory::create();
        $faker2 = Factory::create();
        $faker3 = Factory::create();
        $faker4 = Factory::create();
        $faker5 = Factory::create();
        $faker6 = Factory::create();
        $faker7 = Factory::create();
        $faker8 = Factory::create();
        $faker9 = Factory::create();
        $faker10 = Factory::create();
        $faker11 = Factory::create();
        $username1 = Str::uuid()->toString();
        $username3 = Str::uuid()->toString();
        $username4 = Str::uuid()->toString();
        $username5 = Str::uuid()->toString();
        $username6 = Str::uuid()->toString();
        $username7 = Str::uuid()->toString();
        $username8 = Str::uuid()->toString();
        $username9 = Str::uuid()->toString();
        $username10 = Str::uuid()->toString();
        $username11 = Str::uuid()->toString();
        Participant::insert([
            [
                'meeting_id' => '1',
                'username' => '344c1051-b28a-4934-8159-b12983258f86',
                'title' => null,
                'first_name' => "KongrePad",
                'last_name' => "Developer",
                'identification_number' => null,
                'organisation' => "Pinet Bilişim A.Ş.",
                'email' => "info@pinet.com.tr",
                'phone_country_id' => '223',
                'phone' => "5308266897",
                'password' => '344c1051-b28a-4934-8159-b12983258f86',
                'last_login_ip' => $faker1->ipv4,
                'last_login_agent' => $faker1->userAgent,
                'last_login_datetime' => date('Y-m-d H:i:s'),
                'last_activity' => now(),
                'type' => 'attendee',
                'enrolled' => 0,
                'gdpr_consent' => 0,
                'status' => 1,
            ],
            [
                'meeting_id' => '2',
                'username' => '692ae7aa-1446-4d2f-b74e-396f4541a7a9',
                'title' => null,
                'first_name' => "KongrePad",
                'last_name' => "Developer",
                'identification_number' => null,
                'organisation' => "Pinet Bilişim A.Ş.",
                'email' => "info@pinet.com.tr",
                'phone_country_id' => '223',
                'phone' => "5308266897",
                'password' => '344c1051-b28a-4934-8159-b12983258f86',
                'last_login_ip' => $faker2->ipv4,
                'last_login_agent' => $faker2->userAgent,
                'last_login_datetime' => date('Y-m-d H:i:s'),
                'last_activity' => now(),
                'type' => 'attendee',
                'enrolled' => 0,
                'gdpr_consent' => 0,
                'status' => 1,
            ],
            [
                'meeting_id' => '2',
                'username' => $username3,
                'title' => null,
                'first_name' => "Başak",
                'last_name' => "Öven",
                'identification_number' => null,
                'organisation' => null,
                'email' => $faker3->email,
                'phone_country_id' => null,
                'phone' => null,
                'password' => '344c1051-b28a-4934-8159-b12983258f86',
                'last_login_ip' => $faker3->ipv4,
                'last_login_agent' => $faker3->userAgent,
                'last_login_datetime' => date('Y-m-d H:i:s'),
                'last_activity' => now(),
                'type' => 'attendee',
                'enrolled' => 0,
                'gdpr_consent' => 0,
                'status' => 1,
            ],
            [
                'meeting_id' => '2',
                'username' => $username4,
                'title' => null,
                'first_name' => "Arzu",
                'last_name' => "Oğuz",
                'identification_number' => null,
                'organisation' => null,
                'email' => $faker4->email,
                'phone_country_id' => null,
                'phone' => null,
                'password' => '344c1051-b28a-4934-8159-b12983258f86',
                'last_login_ip' => $faker4->ipv4,
                'last_login_agent' => $faker4->userAgent,
                'last_login_datetime' => date('Y-m-d H:i:s'),
                'last_activity' => now(),
                'type' => 'attendee',
                'enrolled' => 0,
                'gdpr_consent' => 0,
                'status' => 1,
            ],
            [
                'meeting_id' => '2',
                'username' => $username5,
                'title' => null,
                'first_name' => "Başak",
                'last_name' => "Oyan Uluç",
                'identification_number' => null,
                'organisation' => null,
                'email' => $faker5->email,
                'phone_country_id' => null,
                'phone' => null,
                'password' => '344c1051-b28a-4934-8159-b12983258f86',
                'last_login_ip' => $faker5->ipv4,
                'last_login_agent' => $faker5->userAgent,
                'last_login_datetime' => date('Y-m-d H:i:s'),
                'last_activity' => now(),
                'type' => 'attendee',
                'enrolled' => 0,
                'gdpr_consent' => 0,
                'status' => 1,
            ],
            [
                'meeting_id' => '2',
                'username' => $username6,
                'title' => null,
                'first_name' => "M. Ali",
                'last_name' => "Kaplan",
                'identification_number' => null,
                'organisation' => null,
                'email' => $faker6->email,
                'phone_country_id' => null,
                'phone' => null,
                'password' => '344c1051-b28a-4934-8159-b12983258f86',
                'last_login_ip' => $faker6->ipv4,
                'last_login_agent' => $faker6->userAgent,
                'last_login_datetime' => date('Y-m-d H:i:s'),
                'last_activity' => now(),
                'type' => 'attendee',
                'enrolled' => 0,
                'gdpr_consent' => 0,
                'status' => 1,
            ],
            [
                'meeting_id' => '2',
                'username' => $username7,
                'title' => null,
                'first_name' => "Ömer",
                'last_name' => "Dizdar",
                'identification_number' => null,
                'organisation' => null,
                'email' => $faker7->email,
                'phone_country_id' => null,
                'phone' => null,
                'password' => '344c1051-b28a-4934-8159-b12983258f86',
                'last_login_ip' => $faker7->ipv4,
                'last_login_agent' => $faker7->userAgent,
                'last_login_datetime' => date('Y-m-d H:i:s'),
                'last_activity' => now(),
                'type' => 'attendee',
                'enrolled' => 0,
                'gdpr_consent' => 0,
                'status' => 1,
            ],
            [
                'meeting_id' => '2',
                'username' => $username8,
                'title' => null,
                'first_name' => "Alpaslan",
                'last_name' => "Özgün",
                'identification_number' => null,
                'organisation' => null,
                'email' => $faker8->email,
                'phone_country_id' => null,
                'phone' => null,
                'password' => '344c1051-b28a-4934-8159-b12983258f86',
                'last_login_ip' => $faker8->ipv4,
                'last_login_agent' => $faker8->userAgent,
                'last_login_datetime' => date('Y-m-d H:i:s'),
                'last_activity' => now(),
                'type' => 'attendee',
                'enrolled' => 0,
                'gdpr_consent' => 0,
                'status' => 1,
            ],
            [
                'meeting_id' => '2',
                'username' => $username9,
                'title' => null,
                'first_name' => "Mustafa",
                'last_name' => "Erman",
                'identification_number' => null,
                'organisation' => null,
                'email' => $faker9->email,
                'phone_country_id' => null,
                'phone' => null,
                'password' => '344c1051-b28a-4934-8159-b12983258f86',
                'last_login_ip' => $faker9->ipv4,
                'last_login_agent' => $faker9->userAgent,
                'last_login_datetime' => date('Y-m-d H:i:s'),
                'last_activity' => now(),
                'type' => 'attendee',
                'enrolled' => 0,
                'gdpr_consent' => 0,
                'status' => 1,
            ],
            [
                'meeting_id' => '2',
                'username' => $username10,
                'title' => null,
                'first_name' => "Fatih",
                'last_name' => "Köse",
                'identification_number' => null,
                'organisation' => null,
                'email' => $faker10->email,
                'phone_country_id' => null,
                'phone' => null,
                'password' => '344c1051-b28a-4934-8159-b12983258f86',
                'last_login_ip' => $faker10->ipv4,
                'last_login_agent' => $faker10->userAgent,
                'last_login_datetime' => date('Y-m-d H:i:s'),
                'last_activity' => now(),
                'type' => 'attendee',
                'enrolled' => 0,
                'gdpr_consent' => 0,
                'status' => 1,
            ],
            [
                'meeting_id' => '2',
                'username' => $username11,
                'title' => null,
                'first_name' => "İsmail",
                'last_name' => "Çelik",
                'identification_number' => null,
                'organisation' => null,
                'email' => $faker11->email,
                'phone_country_id' => null,
                'phone' => null,
                'password' => '344c1051-b28a-4934-8159-b12983258f86',
                'last_login_ip' => $faker11->ipv4,
                'last_login_agent' => $faker11->userAgent,
                'last_login_datetime' => date('Y-m-d H:i:s'),
                'last_activity' => now(),
                'type' => 'attendee',
                'enrolled' => 0,
                'gdpr_consent' => 0,
                'status' => 1,
            ],
        ]);
    }
}
