<?php

namespace Database\Seeders;

use App\Models\System\Country\Country;
use Illuminate\Database\Seeder;

class SystemCountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::insert(
            [
                ['code' => 'afghanistan',  'name' => 'Afghanistan', 'short_name_2d' => 'af','short_name_3d' => 'afg', 'phone_code' => '93',],
                ['code' => 'albania',  'name' => 'Albania', 'short_name_2d' => 'al','short_name_3d' => 'alb', 'phone_code' => '355',],
                ['code' => 'algeria',  'name' => 'Algeria', 'short_name_2d' => 'dz','short_name_3d' => 'dza', 'phone_code' => '213',],
                ['code' => 'american-samoa',  'name' => 'American Samoa', 'short_name_2d' => 'as','short_name_3d' => 'asm', 'phone_code' => '1-684',],
                ['code' => 'andorra',  'name' => 'Andorra', 'short_name_2d' => 'ad','short_name_3d' => 'and', 'phone_code' => '376',],
                ['code' => 'angola',  'name' => 'Angola', 'short_name_2d' => 'ao','short_name_3d' => 'ago', 'phone_code' => '244',],
                ['code' => 'anguilla',  'name' => 'Anguilla', 'short_name_2d' => 'aı','short_name_3d' => 'aıa', 'phone_code' => '1-264',],
                ['code' => 'antarctica',  'name' => 'Antarctica', 'short_name_2d' => 'aq','short_name_3d' => 'ata', 'phone_code' => '672',],
                ['code' => 'antigua-and-barbuda',  'name' => 'Antigua and Barbuda', 'short_name_2d' => 'ag','short_name_3d' => 'atg', 'phone_code' => '1-268',],
                ['code' => 'argentina',  'name' => 'Argentina', 'short_name_2d' => 'ar','short_name_3d' => 'arg', 'phone_code' => '54',],
                ['code' => 'armenia',  'name' => 'Armenia', 'short_name_2d' => 'am','short_name_3d' => 'arm', 'phone_code' => '374',],
                ['code' => 'aruba',  'name' => 'Aruba', 'short_name_2d' => 'aw','short_name_3d' => 'abw', 'phone_code' => '297',],
                ['code' => 'australia',  'name' => 'Australia', 'short_name_2d' => 'au','short_name_3d' => 'aus', 'phone_code' => '61',],
                ['code' => 'austria',  'name' => 'Austria', 'short_name_2d' => 'at','short_name_3d' => 'aut', 'phone_code' => '43',],
                ['code' => 'azerbaijan',  'name' => 'Azerbaijan', 'short_name_2d' => 'az','short_name_3d' => 'aze', 'phone_code' => '994',],
                ['code' => 'bahamas',  'name' => 'Bahamas', 'short_name_2d' => 'bs','short_name_3d' => 'bhs', 'phone_code' => '1-242',],
                ['code' => 'bahrain',  'name' => 'Bahrain', 'short_name_2d' => 'bh','short_name_3d' => 'bhr', 'phone_code' => '973',],
                ['code' => 'bangladesh',  'name' => 'Bangladesh', 'short_name_2d' => 'bd','short_name_3d' => 'bgd', 'phone_code' => '880',],
                ['code' => 'barbados',  'name' => 'Barbados', 'short_name_2d' => 'bb','short_name_3d' => 'brb', 'phone_code' => '1-246',],
                ['code' => 'belarus',  'name' => 'Belarus', 'short_name_2d' => 'by','short_name_3d' => 'blr', 'phone_code' => '375',],
                ['code' => 'belgium',  'name' => 'Belgium', 'short_name_2d' => 'be','short_name_3d' => 'bel', 'phone_code' => '32',],
                ['code' => 'belize',  'name' => 'Belize', 'short_name_2d' => 'bz','short_name_3d' => 'blz', 'phone_code' => '501',],
                ['code' => 'benin',  'name' => 'Benin', 'short_name_2d' => 'bj','short_name_3d' => 'ben', 'phone_code' => '229',],
                ['code' => 'bermuda',  'name' => 'Bermuda', 'short_name_2d' => 'bm','short_name_3d' => 'bmu', 'phone_code' => '1-441',],
                ['code' => 'bhutan',  'name' => 'Bhutan', 'short_name_2d' => 'bt','short_name_3d' => 'btn', 'phone_code' => '975',],
                ['code' => 'bolivia',  'name' => 'Bolivia', 'short_name_2d' => 'bo','short_name_3d' => 'bol', 'phone_code' => '591',],
                ['code' => 'bosnia-and-herzegovina',  'name' => 'Bosnia and Herzegovina', 'short_name_2d' => 'ba','short_name_3d' => 'bıh', 'phone_code' => '387',],
                ['code' => 'botswana',  'name' => 'Botswana', 'short_name_2d' => 'bw','short_name_3d' => 'bwa', 'phone_code' => '267',],
                ['code' => 'brazil',  'name' => 'Brazil', 'short_name_2d' => 'br','short_name_3d' => 'bra', 'phone_code' => '55',],
                ['code' => 'british-ındian-ocean-territory',  'name' => 'British Indian Ocean Territory', 'short_name_2d' => 'ıo','short_name_3d' => 'ıot', 'phone_code' => '246',],
                ['code' => 'british-virgin-ıslands',  'name' => 'British Virgin Islands', 'short_name_2d' => 'vg','short_name_3d' => 'vgb', 'phone_code' => '1-284',],
                ['code' => 'brunei',  'name' => 'Brunei', 'short_name_2d' => 'bn','short_name_3d' => 'brn', 'phone_code' => '673',],
                ['code' => 'bulgaria',  'name' => 'Bulgaria', 'short_name_2d' => 'bg','short_name_3d' => 'bgr', 'phone_code' => '359',],
                ['code' => 'burkina-faso',  'name' => 'Burkina Faso', 'short_name_2d' => 'bf','short_name_3d' => 'bfa', 'phone_code' => '226',],
                ['code' => 'burundi',  'name' => 'Burundi', 'short_name_2d' => 'bı','short_name_3d' => 'bdı', 'phone_code' => '257',],
                ['code' => 'cambodia',  'name' => 'Cambodia', 'short_name_2d' => 'kh','short_name_3d' => 'khm', 'phone_code' => '855',],
                ['code' => 'cameroon',  'name' => 'Cameroon', 'short_name_2d' => 'cm','short_name_3d' => 'cmr', 'phone_code' => '237',],
                ['code' => 'canada',  'name' => 'Canada', 'short_name_2d' => 'ca','short_name_3d' => 'can', 'phone_code' => '1',],
                ['code' => 'cape-verde',  'name' => 'Cape Verde', 'short_name_2d' => 'cv','short_name_3d' => 'cpv', 'phone_code' => '238',],
                ['code' => 'cayman-ıslands',  'name' => 'Cayman Islands', 'short_name_2d' => 'ky','short_name_3d' => 'cym', 'phone_code' => '1-345',],
                ['code' => 'central-african-republic',  'name' => 'Central African Republic', 'short_name_2d' => 'cf','short_name_3d' => 'caf', 'phone_code' => '236',],
                ['code' => 'chad',  'name' => 'Chad', 'short_name_2d' => 'td','short_name_3d' => 'tcd', 'phone_code' => '235',],
                ['code' => 'chile',  'name' => 'Chile', 'short_name_2d' => 'cl','short_name_3d' => 'chl', 'phone_code' => '56',],
                ['code' => 'china',  'name' => 'China', 'short_name_2d' => 'cn','short_name_3d' => 'chn', 'phone_code' => '86',],
                ['code' => 'christmas-ısland',  'name' => 'Christmas Island', 'short_name_2d' => 'cx','short_name_3d' => 'cxr', 'phone_code' => '61',],
                ['code' => 'cocos-ıslands',  'name' => 'Cocos Islands', 'short_name_2d' => 'cc','short_name_3d' => 'cck', 'phone_code' => '61',],
                ['code' => 'colombia',  'name' => 'Colombia', 'short_name_2d' => 'co','short_name_3d' => 'col', 'phone_code' => '57',],
                ['code' => 'comoros',  'name' => 'Comoros', 'short_name_2d' => 'km','short_name_3d' => 'com', 'phone_code' => '269',],
                ['code' => 'cook-ıslands',  'name' => 'Cook Islands', 'short_name_2d' => 'ck','short_name_3d' => 'cok', 'phone_code' => '682',],
                ['code' => 'costa-rica',  'name' => 'Costa Rica', 'short_name_2d' => 'cr','short_name_3d' => 'crı', 'phone_code' => '506',],
                ['code' => 'croatia',  'name' => 'Croatia', 'short_name_2d' => 'hr','short_name_3d' => 'hrv', 'phone_code' => '385',],
                ['code' => 'cuba',  'name' => 'Cuba', 'short_name_2d' => 'cu','short_name_3d' => 'cub', 'phone_code' => '53',],
                ['code' => 'curacao',  'name' => 'Curacao', 'short_name_2d' => 'cw','short_name_3d' => 'cuw', 'phone_code' => '599',],
                ['code' => 'cyprus',  'name' => 'Cyprus', 'short_name_2d' => 'cy','short_name_3d' => 'cyp', 'phone_code' => '357',],
                ['code' => 'czech-republic',  'name' => 'Czech Republic', 'short_name_2d' => 'cz','short_name_3d' => 'cze', 'phone_code' => '420',],
                ['code' => 'democratic-republic-of-the-congo',  'name' => 'Democratic Republic of the Congo', 'short_name_2d' => 'cd','short_name_3d' => 'cod', 'phone_code' => '243',],
                ['code' => 'denmark',  'name' => 'Denmark', 'short_name_2d' => 'dk','short_name_3d' => 'dnk', 'phone_code' => '45',],
                ['code' => 'djibouti',  'name' => 'Djibouti', 'short_name_2d' => 'dj','short_name_3d' => 'djı', 'phone_code' => '253',],
                ['code' => 'dominica',  'name' => 'Dominica', 'short_name_2d' => 'dm','short_name_3d' => 'dma', 'phone_code' => '1-767',],
                ['code' => 'dominican-republic',  'name' => 'Dominican Republic', 'short_name_2d' => 'do','short_name_3d' => 'dom', 'phone_code' => '1-849',],
                ['code' => 'dominican-republic',  'name' => 'Dominican Republic', 'short_name_2d' => 'do','short_name_3d' => 'dom', 'phone_code' => '1-829',],
                ['code' => 'dominican-republic',  'name' => 'Dominican Republic', 'short_name_2d' => 'do','short_name_3d' => 'dom', 'phone_code' => '1-809',],
                ['code' => 'east-timor',  'name' => 'East Timor', 'short_name_2d' => 'tl','short_name_3d' => 'tls', 'phone_code' => '670',],
                ['code' => 'ecuador',  'name' => 'Ecuador', 'short_name_2d' => 'ec','short_name_3d' => 'ecu', 'phone_code' => '593',],
                ['code' => 'egypt',  'name' => 'Egypt', 'short_name_2d' => 'eg','short_name_3d' => 'egy', 'phone_code' => '20',],
                ['code' => 'el-salvador',  'name' => 'El Salvador', 'short_name_2d' => 'sv','short_name_3d' => 'slv', 'phone_code' => '503',],
                ['code' => 'equatorial-guinea',  'name' => 'Equatorial Guinea', 'short_name_2d' => 'gq','short_name_3d' => 'gnq', 'phone_code' => '240',],
                ['code' => 'eritrea',  'name' => 'Eritrea', 'short_name_2d' => 'er','short_name_3d' => 'erı', 'phone_code' => '291',],
                ['code' => 'estonia',  'name' => 'Estonia', 'short_name_2d' => 'ee','short_name_3d' => 'est', 'phone_code' => '372',],
                ['code' => 'ethiopia',  'name' => 'Ethiopia', 'short_name_2d' => 'et','short_name_3d' => 'eth', 'phone_code' => '251',],
                ['code' => 'falkland-ıslands',  'name' => 'Falkland Islands', 'short_name_2d' => 'fk','short_name_3d' => 'flk', 'phone_code' => '500',],
                ['code' => 'faroe-ıslands',  'name' => 'Faroe Islands', 'short_name_2d' => 'fo','short_name_3d' => 'fro', 'phone_code' => '298',],
                ['code' => 'fiji',  'name' => 'Fiji', 'short_name_2d' => 'fj','short_name_3d' => 'fjı', 'phone_code' => '679',],
                ['code' => 'finland',  'name' => 'Finland', 'short_name_2d' => 'fı','short_name_3d' => 'fın', 'phone_code' => '358',],
                ['code' => 'france',  'name' => 'France', 'short_name_2d' => 'fr','short_name_3d' => 'fra', 'phone_code' => '33',],
                ['code' => 'french-polynesia',  'name' => 'French Polynesia', 'short_name_2d' => 'pf','short_name_3d' => 'pyf', 'phone_code' => '689',],
                ['code' => 'gabon',  'name' => 'Gabon', 'short_name_2d' => 'ga','short_name_3d' => 'gab', 'phone_code' => '241',],
                ['code' => 'gambia',  'name' => 'Gambia', 'short_name_2d' => 'gm','short_name_3d' => 'gmb', 'phone_code' => '220',],
                ['code' => 'georgia',  'name' => 'Georgia', 'short_name_2d' => 'ge','short_name_3d' => 'geo', 'phone_code' => '995',],
                ['code' => 'germany',  'name' => 'Germany', 'short_name_2d' => 'de','short_name_3d' => 'deu', 'phone_code' => '49',],
                ['code' => 'ghana',  'name' => 'Ghana', 'short_name_2d' => 'gh','short_name_3d' => 'gha', 'phone_code' => '233',],
                ['code' => 'gibraltar',  'name' => 'Gibraltar', 'short_name_2d' => 'gı','short_name_3d' => 'gıb', 'phone_code' => '350',],
                ['code' => 'greece',  'name' => 'Greece', 'short_name_2d' => 'gr','short_name_3d' => 'grc', 'phone_code' => '30',],
                ['code' => 'greenland',  'name' => 'Greenland', 'short_name_2d' => 'gl','short_name_3d' => 'grl', 'phone_code' => '299',],
                ['code' => 'grenada',  'name' => 'Grenada', 'short_name_2d' => 'gd','short_name_3d' => 'grd', 'phone_code' => '1-473',],
                ['code' => 'guam',  'name' => 'Guam', 'short_name_2d' => 'gu','short_name_3d' => 'gum', 'phone_code' => '1-671',],
                ['code' => 'guatemala',  'name' => 'Guatemala', 'short_name_2d' => 'gt','short_name_3d' => 'gtm', 'phone_code' => '502',],
                ['code' => 'guernsey',  'name' => 'Guernsey', 'short_name_2d' => 'gg','short_name_3d' => 'ggy', 'phone_code' => '44-1481',],
                ['code' => 'guinea',  'name' => 'Guinea', 'short_name_2d' => 'gn','short_name_3d' => 'gın', 'phone_code' => '224',],
                ['code' => 'guinea-bissau',  'name' => 'Guinea-Bissau', 'short_name_2d' => 'gw','short_name_3d' => 'gnb', 'phone_code' => '245',],
                ['code' => 'guyana',  'name' => 'Guyana', 'short_name_2d' => 'gy','short_name_3d' => 'guy', 'phone_code' => '592',],
                ['code' => 'haiti',  'name' => 'Haiti', 'short_name_2d' => 'ht','short_name_3d' => 'htı', 'phone_code' => '509',],
                ['code' => 'honduras',  'name' => 'Honduras', 'short_name_2d' => 'hn','short_name_3d' => 'hnd', 'phone_code' => '504',],
                ['code' => 'hong-kong',  'name' => 'Hong Kong', 'short_name_2d' => 'hk','short_name_3d' => 'hkg', 'phone_code' => '852',],
                ['code' => 'hungary',  'name' => 'Hungary', 'short_name_2d' => 'hu','short_name_3d' => 'hun', 'phone_code' => '36',],
                ['code' => 'ıceland',  'name' => 'Iceland', 'short_name_2d' => 'ıs','short_name_3d' => 'ısl', 'phone_code' => '354',],
                ['code' => 'ındia',  'name' => 'India', 'short_name_2d' => 'ın','short_name_3d' => 'ınd', 'phone_code' => '91',],
                ['code' => 'ındonesia',  'name' => 'Indonesia', 'short_name_2d' => 'ıd','short_name_3d' => 'ıdn', 'phone_code' => '62',],
                ['code' => 'ıran',  'name' => 'Iran', 'short_name_2d' => 'ır','short_name_3d' => 'ırn', 'phone_code' => '98',],
                ['code' => 'ıraq',  'name' => 'Iraq', 'short_name_2d' => 'ıq','short_name_3d' => 'ırq', 'phone_code' => '964',],
                ['code' => 'ıreland',  'name' => 'Ireland', 'short_name_2d' => 'ıe','short_name_3d' => 'ırl', 'phone_code' => '353',],
                ['code' => 'ısle-of-man',  'name' => 'Isle of Man', 'short_name_2d' => 'ım','short_name_3d' => 'ımn', 'phone_code' => '44-1624',],
                ['code' => 'ısrael',  'name' => 'Israel', 'short_name_2d' => 'ıl','short_name_3d' => 'ısr', 'phone_code' => '972',],
                ['code' => 'ıtaly',  'name' => 'Italy', 'short_name_2d' => 'ıt','short_name_3d' => 'ıta', 'phone_code' => '39',],
                ['code' => 'ıvory-coast',  'name' => 'Ivory Coast', 'short_name_2d' => 'cı','short_name_3d' => 'cıv', 'phone_code' => '225',],
                ['code' => 'jamaica',  'name' => 'Jamaica', 'short_name_2d' => 'jm','short_name_3d' => 'jam', 'phone_code' => '1-876',],
                ['code' => 'japan',  'name' => 'Japan', 'short_name_2d' => 'jp','short_name_3d' => 'jpn', 'phone_code' => '81',],
                ['code' => 'jersey',  'name' => 'Jersey', 'short_name_2d' => 'je','short_name_3d' => 'jey', 'phone_code' => '44-1534',],
                ['code' => 'jordan',  'name' => 'Jordan', 'short_name_2d' => 'jo','short_name_3d' => 'jor', 'phone_code' => '962',],
                ['code' => 'kazakhstan',  'name' => 'Kazakhstan', 'short_name_2d' => 'kz','short_name_3d' => 'kaz', 'phone_code' => '7',],
                ['code' => 'kenya',  'name' => 'Kenya', 'short_name_2d' => 'ke','short_name_3d' => 'ken', 'phone_code' => '254',],
                ['code' => 'kiribati',  'name' => 'Kiribati', 'short_name_2d' => 'kı','short_name_3d' => 'kır', 'phone_code' => '686',],
                ['code' => 'kosovo',  'name' => 'Kosovo', 'short_name_2d' => 'xk','short_name_3d' => 'xkx', 'phone_code' => '383',],
                ['code' => 'kuwait',  'name' => 'Kuwait', 'short_name_2d' => 'kw','short_name_3d' => 'kwt', 'phone_code' => '965',],
                ['code' => 'kyrgyzstan',  'name' => 'Kyrgyzstan', 'short_name_2d' => 'kg','short_name_3d' => 'kgz', 'phone_code' => '996',],
                ['code' => 'laos',  'name' => 'Laos', 'short_name_2d' => 'la','short_name_3d' => 'lao', 'phone_code' => '856',],
                ['code' => 'latvia',  'name' => 'Latvia', 'short_name_2d' => 'lv','short_name_3d' => 'lva', 'phone_code' => '371',],
                ['code' => 'lebanon',  'name' => 'Lebanon', 'short_name_2d' => 'lb','short_name_3d' => 'lbn', 'phone_code' => '961',],
                ['code' => 'lesotho',  'name' => 'Lesotho', 'short_name_2d' => 'ls','short_name_3d' => 'lso', 'phone_code' => '266',],
                ['code' => 'liberia',  'name' => 'Liberia', 'short_name_2d' => 'lr','short_name_3d' => 'lbr', 'phone_code' => '231',],
                ['code' => 'libya',  'name' => 'Libya', 'short_name_2d' => 'ly','short_name_3d' => 'lby', 'phone_code' => '218',],
                ['code' => 'liechtenstein',  'name' => 'Liechtenstein', 'short_name_2d' => 'lı','short_name_3d' => 'lıe', 'phone_code' => '423',],
                ['code' => 'lithuania',  'name' => 'Lithuania', 'short_name_2d' => 'lt','short_name_3d' => 'ltu', 'phone_code' => '370',],
                ['code' => 'luxembourg',  'name' => 'Luxembourg', 'short_name_2d' => 'lu','short_name_3d' => 'lux', 'phone_code' => '352',],
                ['code' => 'macau',  'name' => 'Macau', 'short_name_2d' => 'mo','short_name_3d' => 'mac', 'phone_code' => '853',],
                ['code' => 'macedonia',  'name' => 'Macedonia', 'short_name_2d' => 'mk','short_name_3d' => 'mkd', 'phone_code' => '389',],
                ['code' => 'madagascar',  'name' => 'Madagascar', 'short_name_2d' => 'mg','short_name_3d' => 'mdg', 'phone_code' => '261',],
                ['code' => 'malawi',  'name' => 'Malawi', 'short_name_2d' => 'mw','short_name_3d' => 'mwı', 'phone_code' => '265',],
                ['code' => 'malaysia',  'name' => 'Malaysia', 'short_name_2d' => 'my','short_name_3d' => 'mys', 'phone_code' => '60',],
                ['code' => 'maldives',  'name' => 'Maldives', 'short_name_2d' => 'mv','short_name_3d' => 'mdv', 'phone_code' => '960',],
                ['code' => 'mali',  'name' => 'Mali', 'short_name_2d' => 'ml','short_name_3d' => 'mlı', 'phone_code' => '223',],
                ['code' => 'malta',  'name' => 'Malta', 'short_name_2d' => 'mt','short_name_3d' => 'mlt', 'phone_code' => '356',],
                ['code' => 'marshall-ıslands',  'name' => 'Marshall Islands', 'short_name_2d' => 'mh','short_name_3d' => 'mhl', 'phone_code' => '692',],
                ['code' => 'mauritania',  'name' => 'Mauritania', 'short_name_2d' => 'mr','short_name_3d' => 'mrt', 'phone_code' => '222',],
                ['code' => 'mauritius',  'name' => 'Mauritius', 'short_name_2d' => 'mu','short_name_3d' => 'mus', 'phone_code' => '230',],
                ['code' => 'mayotte',  'name' => 'Mayotte', 'short_name_2d' => 'yt','short_name_3d' => 'myt', 'phone_code' => '262',],
                ['code' => 'mexico',  'name' => 'Mexico', 'short_name_2d' => 'mx','short_name_3d' => 'mex', 'phone_code' => '52',],
                ['code' => 'micronesia',  'name' => 'Micronesia', 'short_name_2d' => 'fm','short_name_3d' => 'fsm', 'phone_code' => '691',],
                ['code' => 'moldova',  'name' => 'Moldova', 'short_name_2d' => 'md','short_name_3d' => 'mda', 'phone_code' => '373',],
                ['code' => 'monaco',  'name' => 'Monaco', 'short_name_2d' => 'mc','short_name_3d' => 'mco', 'phone_code' => '377',],
                ['code' => 'mongolia',  'name' => 'Mongolia', 'short_name_2d' => 'mn','short_name_3d' => 'mng', 'phone_code' => '976',],
                ['code' => 'montenegro',  'name' => 'Montenegro', 'short_name_2d' => 'me','short_name_3d' => 'mne', 'phone_code' => '382',],
                ['code' => 'montserrat',  'name' => 'Montserrat', 'short_name_2d' => 'ms','short_name_3d' => 'msr', 'phone_code' => '1-664',],
                ['code' => 'morocco',  'name' => 'Morocco', 'short_name_2d' => 'ma','short_name_3d' => 'mar', 'phone_code' => '212',],
                ['code' => 'mozambique',  'name' => 'Mozambique', 'short_name_2d' => 'mz','short_name_3d' => 'moz', 'phone_code' => '258',],
                ['code' => 'myanmar',  'name' => 'Myanmar', 'short_name_2d' => 'mm','short_name_3d' => 'mmr', 'phone_code' => '95',],
                ['code' => 'namibia',  'name' => 'Namibia', 'short_name_2d' => 'na','short_name_3d' => 'nam', 'phone_code' => '264',],
                ['code' => 'nauru',  'name' => 'Nauru', 'short_name_2d' => 'nr','short_name_3d' => 'nru', 'phone_code' => '674',],
                ['code' => 'nepal',  'name' => 'Nepal', 'short_name_2d' => 'np','short_name_3d' => 'npl', 'phone_code' => '977',],
                ['code' => 'netherlands',  'name' => 'Netherlands', 'short_name_2d' => 'nl','short_name_3d' => 'nld', 'phone_code' => '31',],
                ['code' => 'netherlands-antilles',  'name' => 'Netherlands Antilles', 'short_name_2d' => 'an','short_name_3d' => 'ant', 'phone_code' => '599',],
                ['code' => 'new-caledonia',  'name' => 'New Caledonia', 'short_name_2d' => 'nc','short_name_3d' => 'ncl', 'phone_code' => '687',],
                ['code' => 'new-zealand',  'name' => 'New Zealand', 'short_name_2d' => 'nz','short_name_3d' => 'nzl', 'phone_code' => '64',],
                ['code' => 'nicaragua',  'name' => 'Nicaragua', 'short_name_2d' => 'nı','short_name_3d' => 'nıc', 'phone_code' => '505',],
                ['code' => 'niger',  'name' => 'Niger', 'short_name_2d' => 'ne','short_name_3d' => 'ner', 'phone_code' => '227',],
                ['code' => 'nigeria',  'name' => 'Nigeria', 'short_name_2d' => 'ng','short_name_3d' => 'nga', 'phone_code' => '234',],
                ['code' => 'niue',  'name' => 'Niue', 'short_name_2d' => 'nu','short_name_3d' => 'nıu', 'phone_code' => '683',],
                ['code' => 'north-korea',  'name' => 'North Korea', 'short_name_2d' => 'kp','short_name_3d' => 'prk', 'phone_code' => '850',],
                ['code' => 'northern-mariana-ıslands',  'name' => 'Northern Mariana Islands', 'short_name_2d' => 'mp','short_name_3d' => 'mnp', 'phone_code' => '1-670',],
                ['code' => 'norway',  'name' => 'Norway', 'short_name_2d' => 'no','short_name_3d' => 'nor', 'phone_code' => '47',],
                ['code' => 'oman',  'name' => 'Oman', 'short_name_2d' => 'om','short_name_3d' => 'omn', 'phone_code' => '968',],
                ['code' => 'pakistan',  'name' => 'Pakistan', 'short_name_2d' => 'pk','short_name_3d' => 'pak', 'phone_code' => '92',],
                ['code' => 'palau',  'name' => 'Palau', 'short_name_2d' => 'pw','short_name_3d' => 'plw', 'phone_code' => '680',],
                ['code' => 'palestine',  'name' => 'Palestine', 'short_name_2d' => 'ps','short_name_3d' => 'pse', 'phone_code' => '970',],
                ['code' => 'panama',  'name' => 'Panama', 'short_name_2d' => 'pa','short_name_3d' => 'pan', 'phone_code' => '507',],
                ['code' => 'papua-new-guinea',  'name' => 'Papua New Guinea', 'short_name_2d' => 'pg','short_name_3d' => 'png', 'phone_code' => '675',],
                ['code' => 'paraguay',  'name' => 'Paraguay', 'short_name_2d' => 'py','short_name_3d' => 'pry', 'phone_code' => '595',],
                ['code' => 'peru',  'name' => 'Peru', 'short_name_2d' => 'pe','short_name_3d' => 'per', 'phone_code' => '51',],
                ['code' => 'philippines',  'name' => 'Philippines', 'short_name_2d' => 'ph','short_name_3d' => 'phl', 'phone_code' => '63',],
                ['code' => 'pitcairn',  'name' => 'Pitcairn', 'short_name_2d' => 'pn','short_name_3d' => 'pcn', 'phone_code' => '64',],
                ['code' => 'poland',  'name' => 'Poland', 'short_name_2d' => 'pl','short_name_3d' => 'pol', 'phone_code' => '48',],
                ['code' => 'portugal',  'name' => 'Portugal', 'short_name_2d' => 'pt','short_name_3d' => 'prt', 'phone_code' => '351',],
                ['code' => 'puerto-rico',  'name' => 'Puerto Rico', 'short_name_2d' => 'pr','short_name_3d' => 'prı', 'phone_code' => '1-939',],
                ['code' => 'puerto-rico',  'name' => 'Puerto Rico', 'short_name_2d' => 'pr','short_name_3d' => 'prı', 'phone_code' => '1-787',],
                ['code' => 'qatar',  'name' => 'Qatar', 'short_name_2d' => 'qa','short_name_3d' => 'qat', 'phone_code' => '974',],
                ['code' => 'republic-of-the-congo',  'name' => 'Republic of the Congo', 'short_name_2d' => 'cg','short_name_3d' => 'cog', 'phone_code' => '242',],
                ['code' => 'reunion',  'name' => 'Reunion', 'short_name_2d' => 're','short_name_3d' => 'reu', 'phone_code' => '262',],
                ['code' => 'romania',  'name' => 'Romania', 'short_name_2d' => 'ro','short_name_3d' => 'rou', 'phone_code' => '40',],
                ['code' => 'russia',  'name' => 'Russia', 'short_name_2d' => 'ru','short_name_3d' => 'rus', 'phone_code' => '7',],
                ['code' => 'rwanda',  'name' => 'Rwanda', 'short_name_2d' => 'rw','short_name_3d' => 'rwa', 'phone_code' => '250',],
                ['code' => 'saint-barthelemy',  'name' => 'Saint Barthelemy', 'short_name_2d' => 'bl','short_name_3d' => 'blm', 'phone_code' => '590',],
                ['code' => 'saint-helena',  'name' => 'Saint Helena', 'short_name_2d' => 'sh','short_name_3d' => 'shn', 'phone_code' => '290',],
                ['code' => 'saint-kitts-and-nevis',  'name' => 'Saint Kitts and Nevis', 'short_name_2d' => 'kn','short_name_3d' => 'kna', 'phone_code' => '1-869',],
                ['code' => 'saint-lucia',  'name' => 'Saint Lucia', 'short_name_2d' => 'lc','short_name_3d' => 'lca', 'phone_code' => '1-758',],
                ['code' => 'saint-martin',  'name' => 'Saint Martin', 'short_name_2d' => 'mf','short_name_3d' => 'maf', 'phone_code' => '590',],
                ['code' => 'saint-pierre-and-miquelon',  'name' => 'Saint Pierre and Miquelon', 'short_name_2d' => 'pm','short_name_3d' => 'spm', 'phone_code' => '508',],
                ['code' => 'saint-vincent-and-the-grenadines',  'name' => 'Saint Vincent and the Grenadines', 'short_name_2d' => 'vc','short_name_3d' => 'vct', 'phone_code' => '1-784',],
                ['code' => 'samoa',  'name' => 'Samoa', 'short_name_2d' => 'ws','short_name_3d' => 'wsm', 'phone_code' => '685',],
                ['code' => 'san-marino',  'name' => 'San Marino', 'short_name_2d' => 'sm','short_name_3d' => 'smr', 'phone_code' => '378',],
                ['code' => 'sao-tome-and-principe',  'name' => 'Sao Tome and Principe', 'short_name_2d' => 'st','short_name_3d' => 'stp', 'phone_code' => '239',],
                ['code' => 'saudi-arabia',  'name' => 'Saudi Arabia', 'short_name_2d' => 'sa','short_name_3d' => 'sau', 'phone_code' => '966',],
                ['code' => 'senegal',  'name' => 'Senegal', 'short_name_2d' => 'sn','short_name_3d' => 'sen', 'phone_code' => '221',],
                ['code' => 'serbia',  'name' => 'Serbia', 'short_name_2d' => 'rs','short_name_3d' => 'srb', 'phone_code' => '381',],
                ['code' => 'seychelles',  'name' => 'Seychelles', 'short_name_2d' => 'sc','short_name_3d' => 'syc', 'phone_code' => '248',],
                ['code' => 'sierra-leone',  'name' => 'Sierra Leone', 'short_name_2d' => 'sl','short_name_3d' => 'sle', 'phone_code' => '232',],
                ['code' => 'singapore',  'name' => 'Singapore', 'short_name_2d' => 'sg','short_name_3d' => 'sgp', 'phone_code' => '65',],
                ['code' => 'sint-maarten',  'name' => 'Sint Maarten', 'short_name_2d' => 'sx','short_name_3d' => 'sxm', 'phone_code' => '1-721',],
                ['code' => 'slovakia',  'name' => 'Slovakia', 'short_name_2d' => 'sk','short_name_3d' => 'svk', 'phone_code' => '421',],
                ['code' => 'slovenia',  'name' => 'Slovenia', 'short_name_2d' => 'sı','short_name_3d' => 'svn', 'phone_code' => '386',],
                ['code' => 'solomon-ıslands',  'name' => 'Solomon Islands', 'short_name_2d' => 'sb','short_name_3d' => 'slb', 'phone_code' => '677',],
                ['code' => 'somalia',  'name' => 'Somalia', 'short_name_2d' => 'so','short_name_3d' => 'som', 'phone_code' => '252',],
                ['code' => 'south-africa',  'name' => 'South Africa', 'short_name_2d' => 'za','short_name_3d' => 'zaf', 'phone_code' => '27',],
                ['code' => 'south-korea',  'name' => 'South Korea', 'short_name_2d' => 'kr','short_name_3d' => 'kor', 'phone_code' => '82',],
                ['code' => 'south-sudan',  'name' => 'South Sudan', 'short_name_2d' => 'ss','short_name_3d' => 'ssd', 'phone_code' => '211',],
                ['code' => 'spain',  'name' => 'Spain', 'short_name_2d' => 'es','short_name_3d' => 'esp', 'phone_code' => '34',],
                ['code' => 'sri-lanka',  'name' => 'Sri Lanka', 'short_name_2d' => 'lk','short_name_3d' => 'lka', 'phone_code' => '94',],
                ['code' => 'sudan',  'name' => 'Sudan', 'short_name_2d' => 'sd','short_name_3d' => 'sdn', 'phone_code' => '249',],
                ['code' => 'suriname',  'name' => 'Suriname', 'short_name_2d' => 'sr','short_name_3d' => 'sur', 'phone_code' => '597',],
                ['code' => 'svalbard-and-jan-mayen',  'name' => 'Svalbard and Jan Mayen', 'short_name_2d' => 'sj','short_name_3d' => 'sjm', 'phone_code' => '47',],
                ['code' => 'swaziland',  'name' => 'Swaziland', 'short_name_2d' => 'sz','short_name_3d' => 'swz', 'phone_code' => '268',],
                ['code' => 'sweden',  'name' => 'Sweden', 'short_name_2d' => 'se','short_name_3d' => 'swe', 'phone_code' => '46',],
                ['code' => 'switzerland',  'name' => 'Switzerland', 'short_name_2d' => 'ch','short_name_3d' => 'che', 'phone_code' => '41',],
                ['code' => 'syria',  'name' => 'Syria', 'short_name_2d' => 'sy','short_name_3d' => 'syr', 'phone_code' => '963',],
                ['code' => 'taiwan',  'name' => 'Taiwan', 'short_name_2d' => 'tw','short_name_3d' => 'twn', 'phone_code' => '886',],
                ['code' => 'tajikistan',  'name' => 'Tajikistan', 'short_name_2d' => 'tj','short_name_3d' => 'tjk', 'phone_code' => '992',],
                ['code' => 'tanzania',  'name' => 'Tanzania', 'short_name_2d' => 'tz','short_name_3d' => 'tza', 'phone_code' => '255',],
                ['code' => 'thailand',  'name' => 'Thailand', 'short_name_2d' => 'th','short_name_3d' => 'tha', 'phone_code' => '66',],
                ['code' => 'togo',  'name' => 'Togo', 'short_name_2d' => 'tg','short_name_3d' => 'tgo', 'phone_code' => '228',],
                ['code' => 'tokelau',  'name' => 'Tokelau', 'short_name_2d' => 'tk','short_name_3d' => 'tkl', 'phone_code' => '690',],
                ['code' => 'tonga',  'name' => 'Tonga', 'short_name_2d' => 'to','short_name_3d' => 'ton', 'phone_code' => '676',],
                ['code' => 'trinidad-and-tobago',  'name' => 'Trinidad and Tobago', 'short_name_2d' => 'tt','short_name_3d' => 'tto', 'phone_code' => '1-868',],
                ['code' => 'tunisia',  'name' => 'Tunisia', 'short_name_2d' => 'tn','short_name_3d' => 'tun', 'phone_code' => '216',],
                ['code' => 'turkey',  'name' => 'Turkey', 'short_name_2d' => 'tr','short_name_3d' => 'tur', 'phone_code' => '90',],
                ['code' => 'turkmenistan',  'name' => 'Turkmenistan', 'short_name_2d' => 'tm','short_name_3d' => 'tkm', 'phone_code' => '993',],
                ['code' => 'turks-and-caicos-ıslands',  'name' => 'Turks and Caicos Islands', 'short_name_2d' => 'tc','short_name_3d' => 'tca', 'phone_code' => '1-649',],
                ['code' => 'tuvalu',  'name' => 'Tuvalu', 'short_name_2d' => 'tv','short_name_3d' => 'tuv', 'phone_code' => '688',],
                ['code' => 'u.s.-virgin-ıslands',  'name' => 'U.S. Virgin Islands', 'short_name_2d' => 'vı','short_name_3d' => 'vır', 'phone_code' => '1-340',],
                ['code' => 'uganda',  'name' => 'Uganda', 'short_name_2d' => 'ug','short_name_3d' => 'uga', 'phone_code' => '256',],
                ['code' => 'ukraine',  'name' => 'Ukraine', 'short_name_2d' => 'ua','short_name_3d' => 'ukr', 'phone_code' => '380',],
                ['code' => 'united-arab-emirates',  'name' => 'United Arab Emirates', 'short_name_2d' => 'ae','short_name_3d' => 'are', 'phone_code' => '971',],
                ['code' => 'united-kingdom',  'name' => 'United Kingdom', 'short_name_2d' => 'gb','short_name_3d' => 'gbr', 'phone_code' => '44',],
                ['code' => 'united-states',  'name' => 'United States', 'short_name_2d' => 'us','short_name_3d' => 'usa', 'phone_code' => '1',],
                ['code' => 'uruguay',  'name' => 'Uruguay', 'short_name_2d' => 'uy','short_name_3d' => 'ury', 'phone_code' => '598',],
                ['code' => 'uzbekistan',  'name' => 'Uzbekistan', 'short_name_2d' => 'uz','short_name_3d' => 'uzb', 'phone_code' => '998',],
                ['code' => 'vanuatu',  'name' => 'Vanuatu', 'short_name_2d' => 'vu','short_name_3d' => 'vut', 'phone_code' => '678',],
                ['code' => 'vatican',  'name' => 'Vatican', 'short_name_2d' => 'va','short_name_3d' => 'vat', 'phone_code' => '379',],
                ['code' => 'venezuela',  'name' => 'Venezuela', 'short_name_2d' => 've','short_name_3d' => 'ven', 'phone_code' => '58',],
                ['code' => 'vietnam',  'name' => 'Vietnam', 'short_name_2d' => 'vn','short_name_3d' => 'vnm', 'phone_code' => '84',],
                ['code' => 'wallis-and-futuna',  'name' => 'Wallis and Futuna', 'short_name_2d' => 'wf','short_name_3d' => 'wlf', 'phone_code' => '681',],
                ['code' => 'western-sahara',  'name' => 'Western Sahara', 'short_name_2d' => 'eh','short_name_3d' => 'esh', 'phone_code' => '212',],
                ['code' => 'yemen',  'name' => 'Yemen', 'short_name_2d' => 'ye','short_name_3d' => 'yem', 'phone_code' => '967',],
                ['code' => 'zambia',  'name' => 'Zambia', 'short_name_2d' => 'zm','short_name_3d' => 'zmb', 'phone_code' => '260',],
                ['code' => 'zimbabwe',  'name' => 'Zimbabwe', 'short_name_2d' => 'zw','short_name_3d' => 'zwe', 'phone_code' => '263',],
            ]
        );
    }
}
