<?php

namespace Database\Seeders;

use App\Models\Customer\Setting\Variable\Variable;
use Illuminate\Database\Seeder;

class VariableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $timezone_variables = [
            'Afghanistan (UTC+04:30)',
            'Åland Islands (UTC+02:00)',
            'Albania (UTC+01:00)',
            'Algeria (UTC+01:00)',
            'American Samoa (UTC-11:00)',
            'Andorra (UTC+01:00)',
            'Angola (UTC+01:00)',
            'Anguilla (UTC-04:00)',
            'Antarctica (UTC-03:00)',
            'Antigua and Barbuda (UTC-04:00)',
            'Argentina (UTC-03:00)',
            'Armenia (UTC+04:00)',
            'Aruba (UTC-04:00)',
            'Australia (UTC+10:00)',
            'Austria (UTC+01:00)',
            'Azerbaijan (UTC+04:00)',
            'Bahamas, The (UTC-05:00)',
            'Bahrain (UTC+03:00)',
            'Bangladesh (UTC+06:00)',
            'Barbados (UTC-04:00)',
            'Belarus (UTC+03:00)',
            'Belgium (UTC+01:00)',
            'Belize (UTC-06:00)',
            'Benin (UTC+01:00)',
            'Bermuda (UTC-04:00)',
            'Bhutan (UTC+06:00)',
            'Bolivarian Republic of Venezuela (UTC-04:30)',
            'Bolivia (UTC-04:00)',
            'Bonaire, Sint Eustatius and Saba (UTC-04:00)',
            'Bosnia and Herzegovina (UTC+01:00)',
            'Botswana (UTC+02:00)',
            'Bouvet Island (UTC)',
            'Brazil (UTC-03:00)',
            'British Indian Ocean Territory (UTC+06:00)',
            'Brunei (UTC+08:00)',
            'Bulgaria (UTC+02:00)',
            'Burkina Faso (UTC)',
            'Burundi (UTC+02:00)',
            'Cabo Verde (UTC-01:00)',
            'Cambodia (UTC+07:00)',
            'Cameroon (UTC+01:00)',
            'Canada (UTC-05:00)',
            'Cayman Islands (UTC-05:00)',
            'Central African Republic (UTC+01:00)',
            'Chad (UTC+01:00)',
            'Chile (UTC-03:00)',
            'China (UTC+08:00)',
            'Christmas Island (UTC+07:00)',
            'Cocos (Keeling) Islands (UTC+06:30)',
            'Colombia (UTC-05:00)',
            'Comoros (UTC+03:00)',
            'Congo (UTC+01:00)',
            'Congo (DRC) (UTC+01:00)',
            'Cook Islands (UTC-10:00)',
            'Costa Rica (UTC-06:00)',
            'Côte d\'Ivoire (UTC)',
            'Croatia (UTC+01:00)',
            'Cuba (UTC-05:00)',
            'Curaçao (UTC-04:00)',
            'Cyprus (UTC+02:00)',
            'Czech Republic (UTC+01:00)',
            'Democratic Republic of Timor-Leste (UTC+09:00)',
            'Denmark (UTC+01:00)',
            'Djibouti (UTC+03:00)',
            'Dominica (UTC-04:00)',
            'Dominican Republic (UTC-04:00)',
            'Ecuador (UTC-05:00)',
            'Egypt (UTC+02:00)',
            'El Salvador (UTC-06:00)',
            'Equatorial Guinea (UTC+01:00)',
            'Eritrea (UTC+03:00)',
            'Estonia (UTC+02:00)',
            'Ethiopia (UTC+03:00)',
            'Falkland Islands (Islas Malvinas) (UTC-03:00)',
            'Faroe Islands (UTC)',
            'Fiji Islands (UTC+12:00)',
            'Finland (UTC+02:00)',
            'France (UTC+01:00)',
            'French Guiana (UTC-03:00)',
            'French Polynesia (UTC-10:00)',
            'French Southern and Antarctic Lands (UTC+05:00)',
            'Gabon (UTC+01:00)',
            'Gambia, The (UTC)',
            'Georgia (UTC+04:00)',
            'Germany (UTC+01:00)',
            'Ghana (UTC)',
            'Gibraltar (UTC+01:00)',
            'Greece (UTC+02:00)',
            'Greenland (UTC-03:00)',
            'Grenada (UTC-04:00)',
            'Guadeloupe (UTC-04:00)',
            'Guam (UTC+10:00)',
            'Guatemala (UTC-06:00)',
            'Guernsey (UTC)',
            'Guinea (UTC)',
            'Guinea-Bissau (UTC)',
            'Guyana (UTC-04:00)',
            'Haiti (UTC-05:00)',
            'Heard Island and McDonald Islands (UTC+04:00)',
            'Honduras (UTC-06:00)',
            'Hong Kong SAR (UTC+08:00)',
            'Hungary (UTC+01:00)',
            'Iceland (UTC)',
            'India (UTC+05:30)',
            'Indonesia (UTC+07:00)',
            'Iran (UTC+03:30)',
            'Iraq (UTC+03:00)',
            'Ireland (UTC)',
            'Israel (UTC+02:00)',
            'Italy (UTC+01:00)',
            'Jamaica (UTC-05:00)',
            'Jan Mayen (UTC+01:00)',
            'Japan (UTC+09:00)',
            'Jersey (UTC)',
            'Jordan (UTC+02:00)',
            'Kazakhstan (UTC+06:00)',
            'Kenya (UTC+03:00)',
            'Kiribati (UTC+12:00)',
            'Korea (UTC+09:00)',
            'Kosovo (UTC+01:00)',
            'Kuwait (UTC+03:00)',
            'Kyrgyzstan (UTC+06:00)',
            'Laos (UTC+07:00)',
            'Latvia (UTC+02:00)',
            'Lebanon (UTC+02:00)',
            'Lesotho (UTC+02:00)',
            'Liberia (UTC)',
            'Libya (UTC+02:00)',
            'Liechtenstein (UTC+01:00)',
            'Lithuania (UTC+02:00)',
            'Luxembourg (UTC+01:00)',
            'Macao SAR (UTC+08:00)',
            'Macedonia, Former Yugoslav Republic of (UTC+01:00)',
            'Madagascar (UTC+03:00)',
            'Malawi (UTC+02:00)',
            'Malaysia (UTC+08:00)',
            'Maldives (UTC+05:00)',
            'Mali (UTC)',
            'Malta (UTC+01:00)',
            'Man, Isle of (UTC)',
            'Marshall Islands (UTC+12:00)',
            'Martinique (UTC-04:00)',
            'Mauritania (UTC)',
            'Mauritius (UTC+04:00)',
            'Mayotte (UTC+03:00)',
            'Mexico (UTC-06:00)',
            'Micronesia (UTC+10:00)',
            'Moldova (UTC+02:00)',
            'Monaco (UTC+01:00)',
            'Mongolia (UTC+08:00)',
            'Montenegro (UTC+01:00)',
            'Montserrat (UTC-04:00)',
            'Morocco (UTC)',
            'Mozambique (UTC+02:00)',
            'Myanmar (UTC+06:30)',
            'Namibia (UTC+01:00)',
            'Nauru (UTC+12:00)',
            'Nepal (UTC+05:45)',
            'Netherlands (UTC+01:00)',
            'New Caledonia (UTC+11:00)',
            'New Zealand (UTC+12:00)',
            'Nicaragua (UTC-06:00)',
            'Niger (UTC+01:00)',
            'Nigeria (UTC+01:00)',
            'Niue (UTC-11:00)',
            'Norfolk Island (UTC+11:00)',
            'North Korea (UTC+09:00)',
            'Northern Mariana Islands (UTC+10:00)',
            'Norway (UTC+01:00)',
            'Oman (UTC+04:00)',
            'Pakistan (UTC+05:00)',
            'Palau (UTC+09:00)',
            'Palestinian Authority (UTC+02:00)',
            'Panama (UTC-05:00)',
            'Papua New Guinea (UTC+10:00)',
            'Paraguay (UTC-04:00)',
            'Peru (UTC-05:00)',
            'Philippines (UTC+08:00)',
            'Pitcairn Islands (UTC-08:00)',
            'Poland (UTC+01:00)',
            'Portugal (UTC)',
            'Puerto Rico (UTC-04:00)',
            'Qatar (UTC+03:00)',
            'Reunion (UTC+04:00)',
            'Romania (UTC+02:00)',
            'Russia (UTC+03:00)',
            'Rwanda (UTC+02:00)',
            'Saint Barthélemy (UTC-04:00)',
            'Saint Helena, Ascension and Tristan da Cunha (UTC)',
            'Saint Kitts and Nevis (UTC-04:00)',
            'Saint Lucia (UTC-04:00)',
            'Saint Martin (French part) (UTC-04:00)',
            'Saint Pierre and Miquelon (UTC-03:00)',
            'Saint Vincent and the Grenadines (UTC-04:00)',
            'Samoa (UTC+13:00)',
            'San Marino (UTC+01:00)',
            'São Tomé and Príncipe (UTC)',
            'Saudi Arabia (UTC+03:00)',
            'Senegal (UTC)',
            'Serbia (UTC+01:00)',
            'Seychelles (UTC+04:00)',
            'Sierra Leone (UTC)',
            'Singapore (UTC+08:00)',
            'Sint Maarten (Dutch part) (UTC-04:00)',
            'Slovakia (UTC+01:00)',
            'Slovenia (UTC+01:00)',
            'Solomon Islands (UTC+11:00)',
            'Somalia (UTC+03:00)',
            'South Africa (UTC+02:00)',
            'South Georgia and the South Sandwich Islands (UTC-02:00)',
            'South Sudan (UTC+03:00)',
            'Spain (UTC+01:00)',
            'Sri Lanka (UTC+05:30)',
            'Sudan (UTC+03:00)',
            'Suriname (UTC-03:00)',
            'Svalbard (UTC+01:00)',
            'Swaziland (UTC+02:00)',
            'Sweden (UTC+01:00)',
            'Switzerland (UTC+01:00)',
            'Syria (UTC+02:00)',
            'Taiwan (UTC+08:00)',
            'Tajikistan (UTC+05:00)',
            'Tanzania (UTC+03:00)',
            'Thailand (UTC+07:00)',
            'Togo (UTC)',
            'Tokelau (UTC+13:00)',
            'Tonga (UTC+13:00)',
            'Trinidad and Tobago (UTC-04:00)',
            'Tunisia (UTC+01:00)',
            'Turkey (UTC+02:00)',
            'Turkmenistan (UTC+05:00)',
            'Turks and Caicos Islands (UTC-05:00)',
            'Tuvalu (UTC+12:00)',
            'U.S. Minor Outlying Islands (UTC-11:00)',
            'Uganda (UTC+03:00)',
            'Ukraine (UTC+02:00)',
            'United Arab Emirates (UTC+04:00)',
            'United Kingdom (UTC)',
            'United States (UTC-07:00)',
            'United States (UTC-08:00)',
            'Uruguay (UTC-03:00)',
            'Uzbekistan (UTC+05:00)',
            'Vanuatu (UTC+11:00)',
            'Vatican City (UTC+01:00)',
            'Vietnam (UTC+07:00)',
            'Virgin Islands, U.S. (UTC-04:00)',
            'Virgin Islands, British (UTC-04:00)',
            'Wallis and Futuna (UTC+12:00)',
            'Yemen (UTC+03:00)',
            'Zambia (UTC+02:00)',
            'Zimbabwe (UTC+02:00)',

        ];
        $date_format_variables = [
            'd/m/Y', 'm/d/Y',  'm-d-Y',  'Y-m-d'
        ];
        $time_format_variables = [
            'H:i', 'H:i:s'
        ];
        Variable::insert([
            [
                'sort_order' => '10',
                'group' => 'localisation',
                'title' => 'date-format',
                'variable' => 'date_format',
                'type' => 'select',
                'type_variables' => json_encode($date_format_variables),
                'status' => '1',
            ],
            [
                'sort_order' => '20',
                'group' => 'localisation',
                'title' => 'time-format',
                'variable' => 'time_format',
                'type' => 'select',
                'type_variables' => json_encode($time_format_variables),
                'status' => '1',
            ],
            [
                'sort_order' => '30',
                'group' => 'localisation',
                'title' => 'timezone',
                'variable' => 'timezone',
                'type' => 'select',
                'type_variables' => json_encode($timezone_variables),
                'status' => '1',
            ],
            [
                'sort_order' => '10',
                'group' => 'localisation',
                'title' => 'address',
                'variable' => 'address',
                'type' => 'text',
                'type_variables' => null,
                'status' => '1',
            ],
            [
                'sort_order' => '10',
                'group' => 'system',
                'title' => 'deneme',
                'variable' => 'deneme',
                'type' => 'text',
                'type_variables' => null,
                'status' => '1',
            ],
            [
                'sort_order' => '10',
                'group' => 'system',
                'title' => 'deneme2',
                'variable' => 'deneme2',
                'type' => 'text',
                'type_variables' => null,
                'status' => '1',
            ],
        ]);

    }
}
